// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: count.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countPublished = `-- name: CountPublished :one
SELECT count(*)::bigint AS total
FROM resources r
WHERE r.kind = $1
  AND r.status = 'published'
  AND ($2::bool OR NOT r.is_demo)
`

type CountPublishedParams struct {
	Kind    string
	Column2 bool
}

func (q *Queries) CountPublished(ctx context.Context, arg CountPublishedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublished, arg.Kind, arg.Column2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const tagsBySlugs = `-- name: TagsBySlugs :many
SELECT id, slug
FROM tags
WHERE slug = ANY($1::text[])
`

type TagsBySlugsRow struct {
	ID   uuid.UUID
	Slug string
}

func (q *Queries) TagsBySlugs(ctx context.Context, dollar_1 []string) ([]TagsBySlugsRow, error) {
	rows, err := q.db.Query(ctx, tagsBySlugs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagsBySlugsRow
	for rows.Next() {
		var i TagsBySlugsRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
