// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSession struct {
	ID             uuid.UUID
	AdminID        uuid.UUID
	TokenHash      string
	CsrfSecretHash string
	ExpiresAt      time.Time
	RevokedAt      pgtype.Timestamptz
	CreatedAt      time.Time
	LastSeenAt     time.Time
}

type AdminUser struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Status       string
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AssistantConversation struct {
	ID        uuid.UUID
	AdminID   uuid.UUID
	Title     string
	CreatedAt time.Time
}

type AssistantTurn struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	RequestKey     string
	UserText       string
	ProfileVersion string
	State          []byte
	Status         string
	Reply          string
	CreatedAt      time.Time
}

type AuditLog struct {
	ID           int64
	ActorAdminID pgtype.UUID
	ActorType    string
	Action       string
	TargetType   string
	TargetID     string
	Changes      []byte
	RequestID    *string
	JobID        *string
	CreatedAt    time.Time
}

type ChangeProposal struct {
	ID                uuid.UUID
	ProcessingRunID   uuid.UUID
	ProposalNo        int32
	ResourceID        pgtype.UUID
	BaseEditVersion   *int64
	ProposedKind      string
	ProposedPayload   []byte
	FieldChanges      []byte
	Status            string
	ReviewedBy        pgtype.UUID
	ReviewDecisions   []byte
	ReviewedAt        pgtype.Timestamptz
	AppliedResourceID pgtype.UUID
	AppliedRevisionID pgtype.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ExternalMetricSnapshot struct {
	ID         int64
	ResourceID uuid.UUID
	SourceID   uuid.UUID
	ObservedAt time.Time
	Stars      *int64
	Forks      *int64
	OpenIssues *int64
	Extra      []byte
	CreatedAt  time.Time
}

type FeaturedSlot struct {
	ID         uuid.UUID
	Kind       string
	Placement  string
	Position   int32
	ResourceID uuid.UUID
	StartsAt   time.Time
	EndsAt     pgtype.Timestamptz
	Enabled    bool
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type IdempotencyRequest struct {
	ID             uuid.UUID
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	Status         string
	ResponseStatus *int16
	ResponseBody   []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
	ParentID       pgtype.UUID
	ItemIndex      *int32
	RequestMeta    []byte
}

type IngestCredential struct {
	ID         uuid.UUID
	SourceID   uuid.UUID
	Name       string
	TokenHash  string
	Scopes     []string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedBy  uuid.UUID
	LastUsedAt pgtype.Timestamptz
	CreatedAt  time.Time
}

type InteractionEvent struct {
	ID          uuid.UUID
	ResourceID  uuid.UUID
	EventType   string
	VisitorHash string
	BucketStart time.Time
	AcceptedAt  time.Time
	CreatedAt   time.Time
}

type McpAction struct {
	ID             uuid.UUID
	AdminID        uuid.UUID
	ConversationID pgtype.UUID
	RequestKey     string
	Operation      string
	Arguments      []byte
	Preview        []byte
	Status         string
	Result         []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type McpToken struct {
	ID         uuid.UUID
	AdminID    uuid.UUID
	Name       string
	TokenHash  string
	CanPrepare bool
	CreatedAt  time.Time
	ExpiresAt  time.Time
	RevokedAt  pgtype.Timestamptz
	CanExecute bool
}

type ProcessingRun struct {
	ID            uuid.UUID
	RawRevisionID uuid.UUID
	Stage         string
	PipelineKey   string
	PipelinePlan  []byte
	InputHash     string
	RuleVersion   string
	RerunNo       int32
	RunKey        string
	Status        string
	Output        []byte
	AttemptCount  int32
	LeaseUntil    pgtype.Timestamptz
	RiverJobID    *int64
	ErrorCode     *string
	ErrorMessage  *string
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ProviderBudgetReservation struct {
	ProviderCallID uuid.UUID
	BudgetWindowID uuid.UUID
	ReservedAmount string
	SettledAmount  pgtype.Numeric
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ProviderBudgetWindow struct {
	ID             uuid.UUID
	ScopeKey       string
	Currency       string
	WindowStart    time.Time
	WindowEnd      time.Time
	LimitAmount    string
	ReservedAmount string
	SpentAmount    string
	UpdatedAt      time.Time
}

type ProviderCall struct {
	ID                uuid.UUID
	ProcessingRunID   pgtype.UUID
	SourceRunID       pgtype.UUID
	ProviderKey       string
	Model             *string
	ProfileVersion    *string
	RequestKey        string
	AttemptNo         int32
	Status            string
	ProviderRequestID *string
	ResponsePayload   []byte
	InputTokens       *int64
	OutputTokens      *int64
	Currency          string
	ReservedCost      string
	ActualCost        pgtype.Numeric
	ErrorCode         *string
	CreatedAt         time.Time
	SentAt            pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	PreviewRequestKey *string
	RequestSummary    []byte
	AssistantTurnID   pgtype.UUID
}

type RankingEntry struct {
	RunID                  uuid.UUID
	ResourceID             uuid.UUID
	Kind                   string
	QualityScore           string
	HeatScore              string
	FreshnessScore         string
	RecommendationScore    string
	HeatPosition           int32
	RecommendationPosition int32
	ReasonCode             *string
}

type RankingRun struct {
	ID          uuid.UUID
	Kind        string
	RuleVersion string
	Parameters  []byte
	Status      string
	IsCurrent   bool
	ComputedAt  pgtype.Timestamptz
	ExpiresAt   time.Time
	ErrorCode   *string
	CreatedAt   time.Time
}

type RawItem struct {
	ID                uuid.UUID
	OwnerSourceID     uuid.UUID
	IdentityKey       string
	CanonicalUrl      *string
	CurrentRevisionID pgtype.UUID
	IsBackfill        bool
	FirstDiscoveredAt time.Time
	LastSeenAt        time.Time
}

type RawItemDiscovery struct {
	ID            uuid.UUID
	RawItemID     uuid.UUID
	SourceID      uuid.UUID
	SourceItemKey string
	ObservedUrl   *string
	FirstSeenAt   time.Time
	LastSeenAt    time.Time
	SeenCount     int64
}

type RawItemRevision struct {
	ID                   uuid.UUID
	RawItemID            uuid.UUID
	RevisionNo           int64
	ContentHash          string
	NormalizationVersion string
	Title                string
	Excerpt              *string
	BodyText             *string
	BodyHtml             *string
	Author               *string
	Language             *string
	SourcePublishedAt    pgtype.Timestamptz
	SourceUpdatedAt      pgtype.Timestamptz
	RawPayload           []byte
	FetchedAt            time.Time
	CreatedAt            time.Time
}

type Resource struct {
	ID                uuid.UUID
	Kind              string
	IdentityKey       *string
	Slug              string
	Status            string
	DraftRevisionID   pgtype.UUID
	EditVersion       int64
	FieldLocks        []string
	IsDemo            bool
	FreshnessEligible bool
	FirstPublishedAt  pgtype.Timestamptz
	CreatedAt         time.Time
	UpdatedAt         time.Time
	LastCheckedAt     pgtype.Timestamptz
}

type ResourceEvidence struct {
	ID                 uuid.UUID
	ResourceID         uuid.UUID
	ResourceRevisionID pgtype.UUID
	ProposalID         pgtype.UUID
	RawRevisionID      uuid.UUID
	FieldPath          string
	EvidenceExcerpt    *string
	Locator            []byte
	CreatedAt          time.Time
}

type ResourceMetricsDaily struct {
	ResourceID     uuid.UUID
	MetricDate     pgtype.Date
	DetailViews    int64
	OutboundClicks int64
	UpdatedAt      time.Time
}

type ResourcePublication struct {
	ResourceID           uuid.UUID
	RevisionID           uuid.UUID
	Kind                 string
	Title                string
	Aliases              []string
	Summary              string
	BodyMarkdown         *string
	CoverUrls            []string
	PrimaryCategoryID    pgtype.UUID
	QualityScore         int16
	RecommendationReason *string
	Details              []byte
	SearchText           string
	ContentUpdatedAt     time.Time
	ProjectedAt          time.Time
}

type ResourceRevision struct {
	ID            uuid.UUID
	ResourceID    uuid.UUID
	RevisionNo    int64
	SchemaVersion int32
	Payload       []byte
	Origin        string
	CreatedBy     pgtype.UUID
	ChangeReason  string
	CreatedAt     time.Time
}

type ResourceTag struct {
	ResourceID uuid.UUID
	TagID      uuid.UUID
	AssignedBy string
	CreatedAt  time.Time
}

type Source struct {
	ID                uuid.UUID
	SourceKey         string
	Name              string
	Kind              string
	ParticipationMode string
	TrustTier         string
	Config            []byte
	CredentialRef     *string
	Enabled           bool
	IntervalSeconds   int32
	Checkpoint        []byte
	NextFetchAt       pgtype.Timestamptz
	LastSuccessAt     pgtype.Timestamptz
	FailureCount      int32
	AutoUpdateFields  []string
	AllowFulltext     bool
	EditVersion       int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SourceRun struct {
	ID                uuid.UUID
	SourceID          uuid.UUID
	SourceEditVersion int64
	ScheduledFor      time.Time
	RunKey            string
	Status            string
	CheckpointBefore  []byte
	CheckpointAfter   []byte
	Stats             []byte
	ErrorCode         *string
	ErrorMessage      *string
	RiverJobID        *int64
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	CreatedAt         time.Time
}

type Tag struct {
	ID           uuid.UUID
	Dimension    string
	Name         string
	Slug         string
	Status       string
	MergedIntoID pgtype.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TagAlias struct {
	ID              uuid.UUID
	TagID           uuid.UUID
	Dimension       string
	Alias           string
	NormalizedAlias string
	IsPrimary       bool
	CreatedAt       time.Time
}
