// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const currentRun = `-- name: CurrentRun :one
SELECT id, kind, rule_version, status, is_current, computed_at, expires_at
FROM ranking_runs
WHERE kind = $1 AND is_current
LIMIT 1
`

type CurrentRunRow struct {
	ID          uuid.UUID
	Kind        string
	RuleVersion string
	Status      string
	IsCurrent   bool
	ComputedAt  pgtype.Timestamptz
	ExpiresAt   time.Time
}

func (q *Queries) CurrentRun(ctx context.Context, kind string) (CurrentRunRow, error) {
	row := q.db.QueryRow(ctx, currentRun, kind)
	var i CurrentRunRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RuleVersion,
		&i.Status,
		&i.IsCurrent,
		&i.ComputedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const runByID = `-- name: RunByID :one
SELECT id, kind, rule_version, status, is_current, computed_at, expires_at
FROM ranking_runs
WHERE id = $1
`

type RunByIDRow struct {
	ID          uuid.UUID
	Kind        string
	RuleVersion string
	Status      string
	IsCurrent   bool
	ComputedAt  pgtype.Timestamptz
	ExpiresAt   time.Time
}

func (q *Queries) RunByID(ctx context.Context, id uuid.UUID) (RunByIDRow, error) {
	row := q.db.QueryRow(ctx, runByID, id)
	var i RunByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.RuleVersion,
		&i.Status,
		&i.IsCurrent,
		&i.ComputedAt,
		&i.ExpiresAt,
	)
	return i, err
}
