// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addReserved = `-- name: AddReserved :execrows
UPDATE provider_budget_windows
SET reserved_amount = reserved_amount + $1, updated_at = $2
WHERE id = $3
`

type AddReservedParams struct {
	Delta     pgtype.Numeric
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) AddReserved(ctx context.Context, arg AddReservedParams) (int64, error) {
	result, err := q.db.Exec(ctx, addReserved, arg.Delta, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertReservation = `-- name: InsertReservation :exec
INSERT INTO provider_budget_reservations (
    provider_call_id, budget_window_id, reserved_amount, status, created_at, updated_at
) VALUES (
    $1, $2, $3, 'held',
    $4, $5
)
`

type InsertReservationParams struct {
	ProviderCallID uuid.UUID
	BudgetWindowID uuid.UUID
	ReservedAmount pgtype.Numeric
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) error {
	_, err := q.db.Exec(ctx, insertReservation,
		arg.ProviderCallID,
		arg.BudgetWindowID,
		arg.ReservedAmount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertWindow = `-- name: InsertWindow :exec
INSERT INTO provider_budget_windows (
    id, scope_key, currency, window_start, window_end, limit_amount, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
ON CONFLICT (scope_key, currency, window_start, window_end) DO NOTHING
`

type InsertWindowParams struct {
	ID          uuid.UUID
	ScopeKey    string
	Currency    string
	WindowStart time.Time
	WindowEnd   time.Time
	LimitAmount pgtype.Numeric
	UpdatedAt   time.Time
}

func (q *Queries) InsertWindow(ctx context.Context, arg InsertWindowParams) error {
	_, err := q.db.Exec(ctx, insertWindow,
		arg.ID,
		arg.ScopeKey,
		arg.Currency,
		arg.WindowStart,
		arg.WindowEnd,
		arg.LimitAmount,
		arg.UpdatedAt,
	)
	return err
}

const listReservations = `-- name: ListReservations :many
SELECT provider_call_id, budget_window_id, reserved_amount, settled_amount, status, created_at, updated_at
FROM provider_budget_reservations
WHERE provider_call_id = $1
ORDER BY budget_window_id
`

func (q *Queries) ListReservations(ctx context.Context, providerCallID uuid.UUID) ([]ProviderBudgetReservation, error) {
	rows, err := q.db.Query(ctx, listReservations, providerCallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderBudgetReservation
	for rows.Next() {
		var i ProviderBudgetReservation
		if err := rows.Scan(
			&i.ProviderCallID,
			&i.BudgetWindowID,
			&i.ReservedAmount,
			&i.SettledAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReservations = `-- name: LockReservations :many
SELECT provider_call_id, budget_window_id, reserved_amount, settled_amount, status, created_at, updated_at
FROM provider_budget_reservations
WHERE provider_call_id = $1
ORDER BY budget_window_id
FOR UPDATE
`

func (q *Queries) LockReservations(ctx context.Context, providerCallID uuid.UUID) ([]ProviderBudgetReservation, error) {
	rows, err := q.db.Query(ctx, lockReservations, providerCallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderBudgetReservation
	for rows.Next() {
		var i ProviderBudgetReservation
		if err := rows.Scan(
			&i.ProviderCallID,
			&i.BudgetWindowID,
			&i.ReservedAmount,
			&i.SettledAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWindows = `-- name: LockWindows :many
SELECT id, scope_key, currency, window_start, window_end, limit_amount, reserved_amount, spent_amount
FROM provider_budget_windows
WHERE currency = $1
  AND (
    (scope_key = $2 AND window_start = $3 AND window_end = $4)
    OR (scope_key = $5 AND window_start = $6 AND window_end = $7)
  )
ORDER BY id
FOR UPDATE
`

type LockWindowsParams struct {
	Currency string
	ScopeA   string
	StartA   time.Time
	EndA     time.Time
	ScopeB   string
	StartB   time.Time
	EndB     time.Time
}

type LockWindowsRow struct {
	ID             uuid.UUID
	ScopeKey       string
	Currency       string
	WindowStart    time.Time
	WindowEnd      time.Time
	LimitAmount    pgtype.Numeric
	ReservedAmount pgtype.Numeric
	SpentAmount    pgtype.Numeric
}

func (q *Queries) LockWindows(ctx context.Context, arg LockWindowsParams) ([]LockWindowsRow, error) {
	rows, err := q.db.Query(ctx, lockWindows,
		arg.Currency,
		arg.ScopeA,
		arg.StartA,
		arg.EndA,
		arg.ScopeB,
		arg.StartB,
		arg.EndB,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockWindowsRow
	for rows.Next() {
		var i LockWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKey,
			&i.Currency,
			&i.WindowStart,
			&i.WindowEnd,
			&i.LimitAmount,
			&i.ReservedAmount,
			&i.SpentAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWindowsByIDs = `-- name: LockWindowsByIDs :many
SELECT id, scope_key, currency, window_start, window_end, limit_amount, reserved_amount, spent_amount
FROM provider_budget_windows
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

type LockWindowsByIDsRow struct {
	ID             uuid.UUID
	ScopeKey       string
	Currency       string
	WindowStart    time.Time
	WindowEnd      time.Time
	LimitAmount    pgtype.Numeric
	ReservedAmount pgtype.Numeric
	SpentAmount    pgtype.Numeric
}

func (q *Queries) LockWindowsByIDs(ctx context.Context, ids []uuid.UUID) ([]LockWindowsByIDsRow, error) {
	rows, err := q.db.Query(ctx, lockWindowsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockWindowsByIDsRow
	for rows.Next() {
		var i LockWindowsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeKey,
			&i.Currency,
			&i.WindowStart,
			&i.WindowEnd,
			&i.LimitAmount,
			&i.ReservedAmount,
			&i.SpentAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseReservation = `-- name: ReleaseReservation :execrows
UPDATE provider_budget_reservations
SET status = 'released', updated_at = $1
WHERE provider_call_id = $2
  AND budget_window_id = $3
  AND status = 'held'
`

type ReleaseReservationParams struct {
	UpdatedAt      time.Time
	ProviderCallID uuid.UUID
	BudgetWindowID uuid.UUID
}

func (q *Queries) ReleaseReservation(ctx context.Context, arg ReleaseReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseReservation, arg.UpdatedAt, arg.ProviderCallID, arg.BudgetWindowID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseWindow = `-- name: ReleaseWindow :execrows
UPDATE provider_budget_windows
SET reserved_amount = reserved_amount - $1, updated_at = $2
WHERE id = $3 AND reserved_amount >= $1
`

type ReleaseWindowParams struct {
	Held      pgtype.Numeric
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) ReleaseWindow(ctx context.Context, arg ReleaseWindowParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseWindow, arg.Held, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleReservation = `-- name: SettleReservation :execrows
UPDATE provider_budget_reservations
SET status = 'settled', settled_amount = $1, updated_at = $2
WHERE provider_call_id = $3
  AND budget_window_id = $4
  AND status = 'held'
`

type SettleReservationParams struct {
	SettledAmount  pgtype.Numeric
	UpdatedAt      time.Time
	ProviderCallID uuid.UUID
	BudgetWindowID uuid.UUID
}

func (q *Queries) SettleReservation(ctx context.Context, arg SettleReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleReservation,
		arg.SettledAmount,
		arg.UpdatedAt,
		arg.ProviderCallID,
		arg.BudgetWindowID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleWindow = `-- name: SettleWindow :execrows
UPDATE provider_budget_windows
SET reserved_amount = reserved_amount - $1,
    spent_amount = spent_amount + $2,
    updated_at = $3
WHERE id = $4 AND reserved_amount >= $1
`

type SettleWindowParams struct {
	Held      pgtype.Numeric
	Actual    pgtype.Numeric
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) SettleWindow(ctx context.Context, arg SettleWindowParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleWindow,
		arg.Held,
		arg.Actual,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
