// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calls.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertCall = `-- name: InsertCall :one
INSERT INTO provider_calls (
    id, processing_run_id, assistant_turn_id, provider_key, model, profile_version,
    request_key, attempt_no, status, currency, reserved_cost, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, 'prepared', $9, $10, $11
)
RETURNING id
`

type InsertCallParams struct {
	ID              uuid.UUID
	ProcessingRunID pgtype.UUID
	AssistantTurnID pgtype.UUID
	ProviderKey     string
	Model           *string
	ProfileVersion  *string
	RequestKey      string
	AttemptNo       int32
	Currency        string
	ReservedCost    pgtype.Numeric
	CreatedAt       time.Time
}

func (q *Queries) InsertCall(ctx context.Context, arg InsertCallParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCall,
		arg.ID,
		arg.ProcessingRunID,
		arg.AssistantTurnID,
		arg.ProviderKey,
		arg.Model,
		arg.ProfileVersion,
		arg.RequestKey,
		arg.AttemptNo,
		arg.Currency,
		arg.ReservedCost,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCallsByStatus = `-- name: ListCallsByStatus :many
SELECT id, provider_key, status, reserved_cost, created_at
FROM provider_calls
WHERE status = $1
ORDER BY created_at DESC, id
LIMIT 100
`

type ListCallsByStatusRow struct {
	ID           uuid.UUID
	ProviderKey  string
	Status       string
	ReservedCost pgtype.Numeric
	CreatedAt    time.Time
}

func (q *Queries) ListCallsByStatus(ctx context.Context, status string) ([]ListCallsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listCallsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCallsByStatusRow
	for rows.Next() {
		var i ListCallsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderKey,
			&i.Status,
			&i.ReservedCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePrepared = `-- name: ListStalePrepared :many
SELECT id
FROM provider_calls
WHERE status = 'prepared' AND created_at < $1
ORDER BY id
LIMIT 100
`

func (q *Queries) ListStalePrepared(ctx context.Context, cutoff time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStalePrepared, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleSent = `-- name: ListStaleSent :many
SELECT id
FROM provider_calls
WHERE status = 'sent' AND sent_at IS NOT NULL AND sent_at < $1
ORDER BY id
LIMIT 100
`

func (q *Queries) ListStaleSent(ctx context.Context, cutoff pgtype.Timestamptz) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStaleSent, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCall = `-- name: LockCall :one
SELECT id, processing_run_id, source_run_id, provider_key, model, profile_version,
       request_key, attempt_no, status, provider_request_id, response_payload,
       input_tokens, output_tokens, currency, reserved_cost, actual_cost, error_code,
       created_at, sent_at, completed_at, preview_request_key, request_summary, assistant_turn_id
FROM provider_calls
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockCall(ctx context.Context, id uuid.UUID) (ProviderCall, error) {
	row := q.db.QueryRow(ctx, lockCall, id)
	var i ProviderCall
	err := row.Scan(
		&i.ID,
		&i.ProcessingRunID,
		&i.SourceRunID,
		&i.ProviderKey,
		&i.Model,
		&i.ProfileVersion,
		&i.RequestKey,
		&i.AttemptNo,
		&i.Status,
		&i.ProviderRequestID,
		&i.ResponsePayload,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Currency,
		&i.ReservedCost,
		&i.ActualCost,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.SentAt,
		&i.CompletedAt,
		&i.PreviewRequestKey,
		&i.RequestSummary,
		&i.AssistantTurnID,
	)
	return i, err
}

const lockCallsByRequestKey = `-- name: LockCallsByRequestKey :many
SELECT id, processing_run_id, source_run_id, provider_key, model, profile_version,
       request_key, attempt_no, status, provider_request_id, response_payload,
       input_tokens, output_tokens, currency, reserved_cost, actual_cost, error_code,
       created_at, sent_at, completed_at, preview_request_key, request_summary, assistant_turn_id
FROM provider_calls
WHERE request_key = $1
ORDER BY attempt_no
FOR UPDATE
`

func (q *Queries) LockCallsByRequestKey(ctx context.Context, requestKey string) ([]ProviderCall, error) {
	rows, err := q.db.Query(ctx, lockCallsByRequestKey, requestKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderCall
	for rows.Next() {
		var i ProviderCall
		if err := rows.Scan(
			&i.ID,
			&i.ProcessingRunID,
			&i.SourceRunID,
			&i.ProviderKey,
			&i.Model,
			&i.ProfileVersion,
			&i.RequestKey,
			&i.AttemptNo,
			&i.Status,
			&i.ProviderRequestID,
			&i.ResponsePayload,
			&i.InputTokens,
			&i.OutputTokens,
			&i.Currency,
			&i.ReservedCost,
			&i.ActualCost,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.SentAt,
			&i.CompletedAt,
			&i.PreviewRequestKey,
			&i.RequestSummary,
			&i.AssistantTurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFailed = `-- name: MarkFailed :execrows
UPDATE provider_calls
SET status = 'failed', error_code = $1, completed_at = $2
WHERE id = $3 AND status IN ('prepared', 'sent', 'unknown')
`

type MarkFailedParams struct {
	ErrorCode   *string
	CompletedAt pgtype.Timestamptz
	ID          uuid.UUID
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFailed, arg.ErrorCode, arg.CompletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSent = `-- name: MarkSent :one
UPDATE provider_calls
SET status = 'sent', sent_at = $1
WHERE id = $2 AND status = 'prepared'
RETURNING id
`

type MarkSentParams struct {
	SentAt pgtype.Timestamptz
	ID     uuid.UUID
}

func (q *Queries) MarkSent(ctx context.Context, arg MarkSentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markSent, arg.SentAt, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markSucceeded = `-- name: MarkSucceeded :execrows
UPDATE provider_calls
SET status = 'succeeded',
    provider_request_id = $1,
    response_payload = $2,
    input_tokens = $3,
    output_tokens = $4,
    actual_cost = $5,
    error_code = $6,
    completed_at = $7
WHERE id = $8 AND status IN ('sent', 'unknown', 'succeeded')
`

type MarkSucceededParams struct {
	ProviderRequestID *string
	ResponsePayload   []byte
	InputTokens       *int64
	OutputTokens      *int64
	ActualCost        pgtype.Numeric
	ErrorCode         *string
	CompletedAt       pgtype.Timestamptz
	ID                uuid.UUID
}

func (q *Queries) MarkSucceeded(ctx context.Context, arg MarkSucceededParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSucceeded,
		arg.ProviderRequestID,
		arg.ResponsePayload,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ActualCost,
		arg.ErrorCode,
		arg.CompletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markUnknown = `-- name: MarkUnknown :execrows
UPDATE provider_calls
SET status = 'unknown', error_code = $1, completed_at = $2
WHERE id = $3 AND status = 'sent'
`

type MarkUnknownParams struct {
	ErrorCode   *string
	CompletedAt pgtype.Timestamptz
	ID          uuid.UUID
}

func (q *Queries) MarkUnknown(ctx context.Context, arg MarkUnknownParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUnknown, arg.ErrorCode, arg.CompletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const readCall = `-- name: ReadCall :one
SELECT id, processing_run_id, source_run_id, provider_key, model, profile_version,
       request_key, attempt_no, status, provider_request_id, response_payload,
       input_tokens, output_tokens, currency, reserved_cost, actual_cost, error_code,
       created_at, sent_at, completed_at, preview_request_key, request_summary, assistant_turn_id
FROM provider_calls
WHERE id = $1
`

func (q *Queries) ReadCall(ctx context.Context, id uuid.UUID) (ProviderCall, error) {
	row := q.db.QueryRow(ctx, readCall, id)
	var i ProviderCall
	err := row.Scan(
		&i.ID,
		&i.ProcessingRunID,
		&i.SourceRunID,
		&i.ProviderKey,
		&i.Model,
		&i.ProfileVersion,
		&i.RequestKey,
		&i.AttemptNo,
		&i.Status,
		&i.ProviderRequestID,
		&i.ResponsePayload,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Currency,
		&i.ReservedCost,
		&i.ActualCost,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.SentAt,
		&i.CompletedAt,
		&i.PreviewRequestKey,
		&i.RequestSummary,
		&i.AssistantTurnID,
	)
	return i, err
}
