// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const anyAdmin = `-- name: AnyAdmin :one
SELECT EXISTS (SELECT 1 FROM admin_users) AS present
`

func (q *Queries) AnyAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, anyAdmin)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const findAdminByUsername = `-- name: FindAdminByUsername :one
SELECT id, username, password_hash, status
FROM admin_users
WHERE username = $1
`

type FindAdminByUsernameRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Status       string
}

func (q *Queries) FindAdminByUsername(ctx context.Context, username string) (FindAdminByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findAdminByUsername, username)
	var i FindAdminByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Status,
	)
	return i, err
}

const insertAdmin = `-- name: InsertAdmin :exec
INSERT INTO admin_users (id, username, password_hash)
VALUES ($1, $2, $3)
`

type InsertAdminParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) InsertAdmin(ctx context.Context, arg InsertAdminParams) error {
	_, err := q.db.Exec(ctx, insertAdmin, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const touchAdminLogin = `-- name: TouchAdminLogin :exec
UPDATE admin_users
SET last_login_at = $2, updated_at = $2
WHERE id = $1
`

type TouchAdminLoginParams struct {
	ID          uuid.UUID
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) TouchAdminLogin(ctx context.Context, arg TouchAdminLoginParams) error {
	_, err := q.db.Exec(ctx, touchAdminLogin, arg.ID, arg.LastLoginAt)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin_users
SET password_hash = $2, updated_at = $3
WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
	UpdatedAt    time.Time
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash, arg.UpdatedAt)
	return err
}
