// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_logs (
    actor_admin_id, actor_type, action, target_type, target_id, changes, request_id, job_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertAuditParams struct {
	ActorAdminID pgtype.UUID
	ActorType    string
	Action       string
	TargetType   string
	TargetID     string
	Changes      json.RawMessage
	RequestID    *string
	JobID        *string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorAdminID,
		arg.ActorType,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Changes,
		arg.RequestID,
		arg.JobID,
	)
	return err
}

const listAuditByTarget = `-- name: ListAuditByTarget :many
SELECT
    id,
    actor_admin_id,
    actor_type,
    action,
    target_type,
    target_id,
    changes,
    request_id,
    job_id,
    created_at
FROM audit_logs
WHERE target_type = $1 AND target_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 100
`

type ListAuditByTargetParams struct {
	TargetType string
	TargetID   string
}

func (q *Queries) ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorAdminID,
			&i.ActorType,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Changes,
			&i.RequestID,
			&i.JobID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
