// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeIdempotency = `-- name: CompleteIdempotency :execrows
UPDATE idempotency_requests
SET status = 'completed',
    response_status = $1,
    response_body = $2
WHERE id = $3
  AND status = 'processing'
`

type CompleteIdempotencyParams struct {
	ResponseStatus *int16
	ResponseBody   []byte
	ID             uuid.UUID
}

func (q *Queries) CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotency, arg.ResponseStatus, arg.ResponseBody, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertIdempotency = `-- name: InsertIdempotency :one
INSERT INTO idempotency_requests (
    id, principal_key, scope, idempotency_key, request_hash, status, expires_at
) VALUES (
    $1, $2, $3, $4, $5, 'processing', $6
)
ON CONFLICT (principal_key, scope, idempotency_key) DO NOTHING
RETURNING id
`

type InsertIdempotencyParams struct {
	ID             uuid.UUID
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	ExpiresAt      time.Time
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertIdempotency,
		arg.ID,
		arg.PrincipalKey,
		arg.Scope,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lockIdempotency = `-- name: LockIdempotency :one
SELECT id, request_hash, status, response_status, response_body
FROM idempotency_requests
WHERE principal_key = $1
  AND scope = $2
  AND idempotency_key = $3
FOR UPDATE
`

type LockIdempotencyParams struct {
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
}

type LockIdempotencyRow struct {
	ID             uuid.UUID
	RequestHash    string
	Status         string
	ResponseStatus *int16
	ResponseBody   []byte
}

func (q *Queries) LockIdempotency(ctx context.Context, arg LockIdempotencyParams) (LockIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, lockIdempotency, arg.PrincipalKey, arg.Scope, arg.IdempotencyKey)
	var i LockIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
	)
	return i, err
}
