// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT
    s.id,
    s.admin_id,
    s.csrf_secret_hash,
    s.expires_at,
    s.revoked_at,
    u.username,
    u.status
FROM admin_sessions s
JOIN admin_users u ON u.id = s.admin_id
WHERE s.token_hash = $1
`

type FindSessionByTokenHashRow struct {
	ID             uuid.UUID
	AdminID        uuid.UUID
	CsrfSecretHash string
	ExpiresAt      time.Time
	RevokedAt      pgtype.Timestamptz
	Username       string
	Status         string
}

func (q *Queries) FindSessionByTokenHash(ctx context.Context, tokenHash string) (FindSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findSessionByTokenHash, tokenHash)
	var i FindSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.CsrfSecretHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Username,
		&i.Status,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO admin_sessions (
    id, admin_id, token_hash, csrf_secret_hash, expires_at, last_seen_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertSessionParams struct {
	ID             uuid.UUID
	AdminID        uuid.UUID
	TokenHash      string
	CsrfSecretHash string
	ExpiresAt      time.Time
	LastSeenAt     time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.AdminID,
		arg.TokenHash,
		arg.CsrfSecretHash,
		arg.ExpiresAt,
		arg.LastSeenAt,
	)
	return err
}

const revokeAdminSessions = `-- name: RevokeAdminSessions :exec
UPDATE admin_sessions
SET revoked_at = $2
WHERE admin_id = $1 AND revoked_at IS NULL
`

type RevokeAdminSessionsParams struct {
	AdminID   uuid.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeAdminSessions(ctx context.Context, arg RevokeAdminSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAdminSessions, arg.AdminID, arg.RevokedAt)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE admin_sessions
SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        uuid.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE admin_sessions
SET last_seen_at = $2
WHERE id = $1
`

type TouchSessionParams struct {
	ID         uuid.UUID
	LastSeenAt time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastSeenAt)
	return err
}
