// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_logs (
    actor_admin_id, actor_type, action, target_type, target_id, changes, request_id, job_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertAuditParams struct {
	ActorAdminID pgtype.UUID
	ActorType    string
	Action       string
	TargetType   string
	TargetID     string
	Changes      json.RawMessage
	RequestID    *string
	JobID        *string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorAdminID,
		arg.ActorType,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Changes,
		arg.RequestID,
		arg.JobID,
	)
	return err
}

const listAdminResources = `-- name: ListAdminResources :many
SELECT r.id, r.kind, r.slug, r.status, r.edit_version, r.updated_at,
       r.draft_revision_id,
       p.revision_id AS published_revision_id,
       COALESCE(dr.payload->>'title', p.title, '')::text AS title
FROM resources r
LEFT JOIN resource_publications p ON p.resource_id = r.id
LEFT JOIN resource_revisions dr ON dr.resource_id = r.id AND dr.id = r.draft_revision_id
WHERE ($1::text = '' OR r.kind = $1)
  AND ($2::text = '' OR r.status = $2)
  AND ($3::text = '' OR strpos(lower(COALESCE(dr.payload->>'title', p.title, '')), lower($3)) > 0)
ORDER BY r.updated_at DESC, r.id
`

type ListAdminResourcesParams struct {
	Column1 string
	Column2 string
	Column3 string
}

type ListAdminResourcesRow struct {
	ID                  uuid.UUID
	Kind                string
	Slug                string
	Status              string
	EditVersion         int64
	UpdatedAt           time.Time
	DraftRevisionID     pgtype.UUID
	PublishedRevisionID pgtype.UUID
	Title               string
}

func (q *Queries) ListAdminResources(ctx context.Context, arg ListAdminResourcesParams) ([]ListAdminResourcesRow, error) {
	rows, err := q.db.Query(ctx, listAdminResources, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminResourcesRow
	for rows.Next() {
		var i ListAdminResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Slug,
			&i.Status,
			&i.EditVersion,
			&i.UpdatedAt,
			&i.DraftRevisionID,
			&i.PublishedRevisionID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
