// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: featured.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const disableFeatured = `-- name: DisableFeatured :one
UPDATE featured_slots
SET enabled = false,
    updated_at = $2
WHERE id = $1
RETURNING id
`

type DisableFeaturedParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) DisableFeatured(ctx context.Context, arg DisableFeaturedParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, disableFeatured, arg.ID, arg.UpdatedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const featuredOverlapExists = `-- name: FeaturedOverlapExists :one
SELECT EXISTS (
    SELECT 1
    FROM featured_slots
    WHERE kind = $1
      AND placement = $2
      AND position = $3
      AND enabled
      AND tstzrange(starts_at, COALESCE(ends_at, 'infinity'::timestamptz), '[)')
          && tstzrange($4::timestamptz, COALESCE($5::timestamptz, 'infinity'::timestamptz), '[)')
) AS slot_exists
`

type FeaturedOverlapExistsParams struct {
	Kind      string
	Placement string
	Position  int32
	StartsAt  time.Time
	EndsAt    pgtype.Timestamptz
}

func (q *Queries) FeaturedOverlapExists(ctx context.Context, arg FeaturedOverlapExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, featuredOverlapExists,
		arg.Kind,
		arg.Placement,
		arg.Position,
		arg.StartsAt,
		arg.EndsAt,
	)
	var slot_exists bool
	err := row.Scan(&slot_exists)
	return slot_exists, err
}

const insertFeatured = `-- name: InsertFeatured :exec
INSERT INTO featured_slots (
    id, kind, placement, position, resource_id, starts_at, ends_at, enabled, created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, true, $8, $9, $9
)
`

type InsertFeaturedParams struct {
	ID         uuid.UUID
	Kind       string
	Placement  string
	Position   int32
	ResourceID uuid.UUID
	StartsAt   time.Time
	EndsAt     pgtype.Timestamptz
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
}

func (q *Queries) InsertFeatured(ctx context.Context, arg InsertFeaturedParams) error {
	_, err := q.db.Exec(ctx, insertFeatured,
		arg.ID,
		arg.Kind,
		arg.Placement,
		arg.Position,
		arg.ResourceID,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listFeatured = `-- name: ListFeatured :many
SELECT f.id, f.kind, f.placement, f.position, f.resource_id, r.slug,
       f.starts_at, f.ends_at, f.enabled
FROM featured_slots f
JOIN resources r ON r.id = f.resource_id
ORDER BY f.kind, f.placement, f.position, f.starts_at, f.id
`

type ListFeaturedRow struct {
	ID         uuid.UUID
	Kind       string
	Placement  string
	Position   int32
	ResourceID uuid.UUID
	Slug       string
	StartsAt   time.Time
	EndsAt     pgtype.Timestamptz
	Enabled    bool
}

func (q *Queries) ListFeatured(ctx context.Context) ([]ListFeaturedRow, error) {
	rows, err := q.db.Query(ctx, listFeatured)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeaturedRow
	for rows.Next() {
		var i ListFeaturedRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Placement,
			&i.Position,
			&i.ResourceID,
			&i.Slug,
			&i.StartsAt,
			&i.EndsAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
