// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locks.sql

package sqlc

import (
	"context"
)

const lockTaxonomyExclusive = `-- name: LockTaxonomyExclusive :exec
SELECT pg_advisory_xact_lock(1313821761::int4, 1::int4)
`

func (q *Queries) LockTaxonomyExclusive(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockTaxonomyExclusive)
	return err
}

const lockTaxonomyShared = `-- name: LockTaxonomyShared :exec
SELECT pg_advisory_xact_lock_shared(1313821761::int4, 1::int4)
`

func (q *Queries) LockTaxonomyShared(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockTaxonomyShared)
	return err
}
