// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSession struct {
	ID             uuid.UUID
	AdminID        uuid.UUID
	TokenHash      string
	CsrfSecretHash string
	ExpiresAt      time.Time
	RevokedAt      pgtype.Timestamptz
	CreatedAt      time.Time
	LastSeenAt     time.Time
}

type AdminUser struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Status       string
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AuditLog struct {
	ID           int64
	ActorAdminID pgtype.UUID
	ActorType    string
	Action       string
	TargetType   string
	TargetID     string
	Changes      json.RawMessage
	RequestID    *string
	JobID        *string
	CreatedAt    time.Time
}

type FeaturedSlot struct {
	ID         uuid.UUID
	Kind       string
	Placement  string
	Position   int32
	ResourceID uuid.UUID
	StartsAt   time.Time
	EndsAt     pgtype.Timestamptz
	Enabled    bool
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type IdempotencyRequest struct {
	ID             uuid.UUID
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	Status         string
	ResponseStatus *int16
	ResponseBody   []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type InteractionEvent struct {
	ID          uuid.UUID
	ResourceID  uuid.UUID
	EventType   string
	VisitorHash string
	BucketStart time.Time
	AcceptedAt  time.Time
	CreatedAt   time.Time
}

type RankingEntry struct {
	RunID                  uuid.UUID
	ResourceID             uuid.UUID
	Kind                   string
	QualityScore           pgtype.Numeric
	HeatScore              pgtype.Numeric
	FreshnessScore         pgtype.Numeric
	RecommendationScore    pgtype.Numeric
	HeatPosition           int32
	RecommendationPosition int32
	ReasonCode             *string
}

type RankingRun struct {
	ID          uuid.UUID
	Kind        string
	RuleVersion string
	Parameters  json.RawMessage
	Status      string
	IsCurrent   bool
	ComputedAt  pgtype.Timestamptz
	ExpiresAt   time.Time
	ErrorCode   *string
	CreatedAt   time.Time
}

type Resource struct {
	ID                uuid.UUID
	Kind              string
	IdentityKey       *string
	Slug              string
	Status            string
	DraftRevisionID   pgtype.UUID
	EditVersion       int64
	FieldLocks        []string
	IsDemo            bool
	FreshnessEligible bool
	FirstPublishedAt  pgtype.Timestamptz
	CreatedAt         time.Time
	UpdatedAt         time.Time
	LastCheckedAt     pgtype.Timestamptz
}

type ResourceMetricsDaily struct {
	ResourceID     uuid.UUID
	MetricDate     pgtype.Date
	DetailViews    int64
	OutboundClicks int64
	UpdatedAt      time.Time
}

type ResourcePublication struct {
	ResourceID           uuid.UUID
	RevisionID           uuid.UUID
	Kind                 string
	Title                string
	Aliases              []string
	Summary              string
	BodyMarkdown         *string
	CoverUrls            []string
	PrimaryCategoryID    pgtype.UUID
	QualityScore         int16
	RecommendationReason *string
	Details              json.RawMessage
	SearchText           string
	ContentUpdatedAt     time.Time
	ProjectedAt          time.Time
}

type ResourceRevision struct {
	ID            uuid.UUID
	ResourceID    uuid.UUID
	RevisionNo    int64
	SchemaVersion int32
	Payload       json.RawMessage
	Origin        string
	CreatedBy     pgtype.UUID
	ChangeReason  string
	CreatedAt     time.Time
}

type ResourceTag struct {
	ResourceID uuid.UUID
	TagID      uuid.UUID
	AssignedBy string
	CreatedAt  time.Time
}

type Tag struct {
	ID           uuid.UUID
	Dimension    string
	Name         string
	Slug         string
	Status       string
	MergedIntoID pgtype.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TagAlias struct {
	ID              uuid.UUID
	TagID           uuid.UUID
	Dimension       string
	Alias           string
	NormalizedAlias string
	IsPrimary       bool
	CreatedAt       time.Time
}
