// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publications.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const copyTagRelations = `-- name: CopyTagRelations :exec
INSERT INTO resource_tags (resource_id, tag_id, assigned_by)
SELECT src.resource_id, $2, src.assigned_by
FROM resource_tags AS src
WHERE src.tag_id = $1
ON CONFLICT (resource_id, tag_id) DO NOTHING
`

type CopyTagRelationsParams struct {
	TagID   uuid.UUID
	TagID_2 uuid.UUID
}

func (q *Queries) CopyTagRelations(ctx context.Context, arg CopyTagRelationsParams) error {
	_, err := q.db.Exec(ctx, copyTagRelations, arg.TagID, arg.TagID_2)
	return err
}

const deleteResourceTags = `-- name: DeleteResourceTags :exec
DELETE FROM resource_tags
WHERE resource_id = $1
`

func (q *Queries) DeleteResourceTags(ctx context.Context, resourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResourceTags, resourceID)
	return err
}

const deleteTagRelations = `-- name: DeleteTagRelations :exec
DELETE FROM resource_tags
WHERE tag_id = $1
`

func (q *Queries) DeleteTagRelations(ctx context.Context, tagID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTagRelations, tagID)
	return err
}

const getPublication = `-- name: GetPublication :one
SELECT resource_id, revision_id, kind, title, aliases, summary, body_markdown,
       cover_urls, primary_category_id, quality_score, recommendation_reason,
       details, search_text, content_updated_at, projected_at
FROM resource_publications
WHERE resource_id = $1
`

func (q *Queries) GetPublication(ctx context.Context, resourceID uuid.UUID) (ResourcePublication, error) {
	row := q.db.QueryRow(ctx, getPublication, resourceID)
	var i ResourcePublication
	err := row.Scan(
		&i.ResourceID,
		&i.RevisionID,
		&i.Kind,
		&i.Title,
		&i.Aliases,
		&i.Summary,
		&i.BodyMarkdown,
		&i.CoverUrls,
		&i.PrimaryCategoryID,
		&i.QualityScore,
		&i.RecommendationReason,
		&i.Details,
		&i.SearchText,
		&i.ContentUpdatedAt,
		&i.ProjectedAt,
	)
	return i, err
}

const insertResourceTag = `-- name: InsertResourceTag :exec
INSERT INTO resource_tags (resource_id, tag_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (resource_id, tag_id) DO NOTHING
`

type InsertResourceTagParams struct {
	ResourceID uuid.UUID
	TagID      uuid.UUID
	AssignedBy string
}

func (q *Queries) InsertResourceTag(ctx context.Context, arg InsertResourceTagParams) error {
	_, err := q.db.Exec(ctx, insertResourceTag, arg.ResourceID, arg.TagID, arg.AssignedBy)
	return err
}

const listAffectedResources = `-- name: ListAffectedResources :many
SELECT resource_id
FROM resource_tags
WHERE tag_id = $1
UNION
SELECT resource_id
FROM resource_publications
WHERE primary_category_id = $1
ORDER BY resource_id
`

func (q *Queries) ListAffectedResources(ctx context.Context, tagID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAffectedResources, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var resource_id uuid.UUID
		if err := rows.Scan(&resource_id); err != nil {
			return nil, err
		}
		items = append(items, resource_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceTagIDs = `-- name: ListResourceTagIDs :many
SELECT tag_id
FROM resource_tags
WHERE resource_id = $1
ORDER BY tag_id
`

func (q *Queries) ListResourceTagIDs(ctx context.Context, resourceID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listResourceTagIDs, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var tag_id uuid.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResourceIDs = `-- name: LockResourceIDs :many
SELECT id
FROM resources
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockResourceIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockResourceIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPublication = `-- name: UpsertPublication :exec
INSERT INTO resource_publications (
    resource_id, revision_id, kind, title, aliases, summary, body_markdown,
    cover_urls, primary_category_id, quality_score, recommendation_reason,
    details, search_text, content_updated_at, projected_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15
)
ON CONFLICT (resource_id) DO UPDATE SET
    revision_id = EXCLUDED.revision_id,
    kind = EXCLUDED.kind,
    title = EXCLUDED.title,
    aliases = EXCLUDED.aliases,
    summary = EXCLUDED.summary,
    body_markdown = EXCLUDED.body_markdown,
    cover_urls = EXCLUDED.cover_urls,
    primary_category_id = EXCLUDED.primary_category_id,
    quality_score = EXCLUDED.quality_score,
    recommendation_reason = EXCLUDED.recommendation_reason,
    details = EXCLUDED.details,
    search_text = EXCLUDED.search_text,
    content_updated_at = EXCLUDED.content_updated_at,
    projected_at = EXCLUDED.projected_at
`

type UpsertPublicationParams struct {
	ResourceID           uuid.UUID
	RevisionID           uuid.UUID
	Kind                 string
	Title                string
	Aliases              []string
	Summary              string
	BodyMarkdown         *string
	CoverUrls            []string
	PrimaryCategoryID    pgtype.UUID
	QualityScore         int16
	RecommendationReason *string
	Details              json.RawMessage
	SearchText           string
	ContentUpdatedAt     time.Time
	ProjectedAt          time.Time
}

func (q *Queries) UpsertPublication(ctx context.Context, arg UpsertPublicationParams) error {
	_, err := q.db.Exec(ctx, upsertPublication,
		arg.ResourceID,
		arg.RevisionID,
		arg.Kind,
		arg.Title,
		arg.Aliases,
		arg.Summary,
		arg.BodyMarkdown,
		arg.CoverUrls,
		arg.PrimaryCategoryID,
		arg.QualityScore,
		arg.RecommendationReason,
		arg.Details,
		arg.SearchText,
		arg.ContentUpdatedAt,
		arg.ProjectedAt,
	)
	return err
}
