// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachDraft = `-- name: AttachDraft :exec
UPDATE resources
SET draft_revision_id = $2,
    field_locks = $3,
    identity_key = $4,
    updated_at = $5
WHERE id = $1
`

type AttachDraftParams struct {
	ID              uuid.UUID
	DraftRevisionID pgtype.UUID
	FieldLocks      []string
	IdentityKey     *string
	UpdatedAt       time.Time
}

func (q *Queries) AttachDraft(ctx context.Context, arg AttachDraftParams) error {
	_, err := q.db.Exec(ctx, attachDraft,
		arg.ID,
		arg.DraftRevisionID,
		arg.FieldLocks,
		arg.IdentityKey,
		arg.UpdatedAt,
	)
	return err
}

const bumpResourceVersions = `-- name: BumpResourceVersions :exec
UPDATE resources
SET edit_version = edit_version + 1,
    updated_at = $2
WHERE id = ANY($1::uuid[])
`

type BumpResourceVersionsParams struct {
	Column1   []uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) BumpResourceVersions(ctx context.Context, arg BumpResourceVersionsParams) error {
	_, err := q.db.Exec(ctx, bumpResourceVersions, arg.Column1, arg.UpdatedAt)
	return err
}

const findIdentity = `-- name: FindIdentity :one
SELECT id
FROM resources
WHERE kind = $1 AND identity_key = $2
`

type FindIdentityParams struct {
	Kind        string
	IdentityKey *string
}

func (q *Queries) FindIdentity(ctx context.Context, arg FindIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findIdentity, arg.Kind, arg.IdentityKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findResourceBySlug = `-- name: FindResourceBySlug :one
SELECT id, kind, identity_key, slug, status, draft_revision_id, edit_version,
       field_locks, is_demo, freshness_eligible, first_published_at, updated_at
FROM resources
WHERE kind = $1 AND slug = $2
`

type FindResourceBySlugParams struct {
	Kind string
	Slug string
}

type FindResourceBySlugRow struct {
	ID                uuid.UUID
	Kind              string
	IdentityKey       *string
	Slug              string
	Status            string
	DraftRevisionID   pgtype.UUID
	EditVersion       int64
	FieldLocks        []string
	IsDemo            bool
	FreshnessEligible bool
	FirstPublishedAt  pgtype.Timestamptz
	UpdatedAt         time.Time
}

func (q *Queries) FindResourceBySlug(ctx context.Context, arg FindResourceBySlugParams) (FindResourceBySlugRow, error) {
	row := q.db.QueryRow(ctx, findResourceBySlug, arg.Kind, arg.Slug)
	var i FindResourceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IdentityKey,
		&i.Slug,
		&i.Status,
		&i.DraftRevisionID,
		&i.EditVersion,
		&i.FieldLocks,
		&i.IsDemo,
		&i.FreshnessEligible,
		&i.FirstPublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertResource = `-- name: InsertResource :exec
INSERT INTO resources (
    id, kind, identity_key, slug, status, edit_version, field_locks,
    is_demo, freshness_eligible, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, 'draft', $5, $6, $7, $8, $9, $9
)
`

type InsertResourceParams struct {
	ID                uuid.UUID
	Kind              string
	IdentityKey       *string
	Slug              string
	EditVersion       int64
	FieldLocks        []string
	IsDemo            bool
	FreshnessEligible bool
	CreatedAt         time.Time
}

func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) error {
	_, err := q.db.Exec(ctx, insertResource,
		arg.ID,
		arg.Kind,
		arg.IdentityKey,
		arg.Slug,
		arg.EditVersion,
		arg.FieldLocks,
		arg.IsDemo,
		arg.FreshnessEligible,
		arg.CreatedAt,
	)
	return err
}

const listResourceKinds = `-- name: ListResourceKinds :many
SELECT id, kind
FROM resources
WHERE id = ANY($1::uuid[])
ORDER BY id
`

type ListResourceKindsRow struct {
	ID   uuid.UUID
	Kind string
}

func (q *Queries) ListResourceKinds(ctx context.Context, dollar_1 []uuid.UUID) ([]ListResourceKindsRow, error) {
	rows, err := q.db.Query(ctx, listResourceKinds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourceKindsRow
	for rows.Next() {
		var i ListResourceKindsRow
		if err := rows.Scan(&i.ID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResource = `-- name: LockResource :one
SELECT id, kind, identity_key, slug, status, draft_revision_id, edit_version,
       field_locks, is_demo, freshness_eligible, first_published_at, updated_at
FROM resources
WHERE id = $1
FOR UPDATE
`

type LockResourceRow struct {
	ID                uuid.UUID
	Kind              string
	IdentityKey       *string
	Slug              string
	Status            string
	DraftRevisionID   pgtype.UUID
	EditVersion       int64
	FieldLocks        []string
	IsDemo            bool
	FreshnessEligible bool
	FirstPublishedAt  pgtype.Timestamptz
	UpdatedAt         time.Time
}

func (q *Queries) LockResource(ctx context.Context, id uuid.UUID) (LockResourceRow, error) {
	row := q.db.QueryRow(ctx, lockResource, id)
	var i LockResourceRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IdentityKey,
		&i.Slug,
		&i.Status,
		&i.DraftRevisionID,
		&i.EditVersion,
		&i.FieldLocks,
		&i.IsDemo,
		&i.FreshnessEligible,
		&i.FirstPublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockResourceBySlug = `-- name: LockResourceBySlug :one
SELECT id, kind, identity_key, slug, status, draft_revision_id, edit_version,
       field_locks, is_demo, freshness_eligible, first_published_at, updated_at
FROM resources
WHERE kind = $1 AND slug = $2
FOR UPDATE
`

type LockResourceBySlugParams struct {
	Kind string
	Slug string
}

type LockResourceBySlugRow struct {
	ID                uuid.UUID
	Kind              string
	IdentityKey       *string
	Slug              string
	Status            string
	DraftRevisionID   pgtype.UUID
	EditVersion       int64
	FieldLocks        []string
	IsDemo            bool
	FreshnessEligible bool
	FirstPublishedAt  pgtype.Timestamptz
	UpdatedAt         time.Time
}

func (q *Queries) LockResourceBySlug(ctx context.Context, arg LockResourceBySlugParams) (LockResourceBySlugRow, error) {
	row := q.db.QueryRow(ctx, lockResourceBySlug, arg.Kind, arg.Slug)
	var i LockResourceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IdentityKey,
		&i.Slug,
		&i.Status,
		&i.DraftRevisionID,
		&i.EditVersion,
		&i.FieldLocks,
		&i.IsDemo,
		&i.FreshnessEligible,
		&i.FirstPublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setFirstPublishedAt = `-- name: SetFirstPublishedAt :exec
UPDATE resources
SET first_published_at = $2
WHERE id = $1
`

type SetFirstPublishedAtParams struct {
	ID               uuid.UUID
	FirstPublishedAt pgtype.Timestamptz
}

func (q *Queries) SetFirstPublishedAt(ctx context.Context, arg SetFirstPublishedAtParams) error {
	_, err := q.db.Exec(ctx, setFirstPublishedAt, arg.ID, arg.FirstPublishedAt)
	return err
}

const updateResourceDraft = `-- name: UpdateResourceDraft :one
UPDATE resources
SET draft_revision_id = $2,
    edit_version = $3,
    field_locks = $4,
    identity_key = $5,
    updated_at = $6
WHERE id = $1 AND edit_version = $7
RETURNING edit_version
`

type UpdateResourceDraftParams struct {
	ID              uuid.UUID
	DraftRevisionID pgtype.UUID
	EditVersion     int64
	FieldLocks      []string
	IdentityKey     *string
	UpdatedAt       time.Time
	EditVersion_2   int64
}

func (q *Queries) UpdateResourceDraft(ctx context.Context, arg UpdateResourceDraftParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateResourceDraft,
		arg.ID,
		arg.DraftRevisionID,
		arg.EditVersion,
		arg.FieldLocks,
		arg.IdentityKey,
		arg.UpdatedAt,
		arg.EditVersion_2,
	)
	var edit_version int64
	err := row.Scan(&edit_version)
	return edit_version, err
}

const updateResourcePublished = `-- name: UpdateResourcePublished :one
UPDATE resources
SET status = 'published',
    draft_revision_id = NULL,
    edit_version = $2,
    identity_key = $3,
    first_published_at = COALESCE(first_published_at, $4),
    updated_at = $5
WHERE id = $1 AND edit_version = $6
RETURNING edit_version, first_published_at
`

type UpdateResourcePublishedParams struct {
	ID               uuid.UUID
	EditVersion      int64
	IdentityKey      *string
	FirstPublishedAt pgtype.Timestamptz
	UpdatedAt        time.Time
	EditVersion_2    int64
}

type UpdateResourcePublishedRow struct {
	EditVersion      int64
	FirstPublishedAt pgtype.Timestamptz
}

func (q *Queries) UpdateResourcePublished(ctx context.Context, arg UpdateResourcePublishedParams) (UpdateResourcePublishedRow, error) {
	row := q.db.QueryRow(ctx, updateResourcePublished,
		arg.ID,
		arg.EditVersion,
		arg.IdentityKey,
		arg.FirstPublishedAt,
		arg.UpdatedAt,
		arg.EditVersion_2,
	)
	var i UpdateResourcePublishedRow
	err := row.Scan(&i.EditVersion, &i.FirstPublishedAt)
	return i, err
}

const updateResourceVisibility = `-- name: UpdateResourceVisibility :one
UPDATE resources
SET status = $2,
    edit_version = $3,
    updated_at = $4
WHERE id = $1 AND edit_version = $5
RETURNING edit_version
`

type UpdateResourceVisibilityParams struct {
	ID            uuid.UUID
	Status        string
	EditVersion   int64
	UpdatedAt     time.Time
	EditVersion_2 int64
}

func (q *Queries) UpdateResourceVisibility(ctx context.Context, arg UpdateResourceVisibilityParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateResourceVisibility,
		arg.ID,
		arg.Status,
		arg.EditVersion,
		arg.UpdatedAt,
		arg.EditVersion_2,
	)
	var edit_version int64
	err := row.Scan(&edit_version)
	return edit_version, err
}
