// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revisions.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getRevision = `-- name: GetRevision :one
SELECT id, resource_id, revision_no, schema_version, payload, origin, created_by, change_reason, created_at
FROM resource_revisions
WHERE resource_id = $1 AND id = $2
`

type GetRevisionParams struct {
	ResourceID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) GetRevision(ctx context.Context, arg GetRevisionParams) (ResourceRevision, error) {
	row := q.db.QueryRow(ctx, getRevision, arg.ResourceID, arg.ID)
	var i ResourceRevision
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.RevisionNo,
		&i.SchemaVersion,
		&i.Payload,
		&i.Origin,
		&i.CreatedBy,
		&i.ChangeReason,
		&i.CreatedAt,
	)
	return i, err
}

const insertRevision = `-- name: InsertRevision :exec
INSERT INTO resource_revisions (
    id, resource_id, revision_no, schema_version, payload, origin, created_by, change_reason, created_at
) VALUES (
    $1, $2, $3, 1, $4, $5, $6, $7, $8
)
`

type InsertRevisionParams struct {
	ID           uuid.UUID
	ResourceID   uuid.UUID
	RevisionNo   int64
	Payload      json.RawMessage
	Origin       string
	CreatedBy    pgtype.UUID
	ChangeReason string
	CreatedAt    time.Time
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.Exec(ctx, insertRevision,
		arg.ID,
		arg.ResourceID,
		arg.RevisionNo,
		arg.Payload,
		arg.Origin,
		arg.CreatedBy,
		arg.ChangeReason,
		arg.CreatedAt,
	)
	return err
}

const listRevisions = `-- name: ListRevisions :many
SELECT id, resource_id, revision_no, schema_version, payload, origin, created_by, change_reason, created_at
FROM resource_revisions
WHERE resource_id = $1
ORDER BY revision_no DESC
`

func (q *Queries) ListRevisions(ctx context.Context, resourceID uuid.UUID) ([]ResourceRevision, error) {
	rows, err := q.db.Query(ctx, listRevisions, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceRevision
	for rows.Next() {
		var i ResourceRevision
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.RevisionNo,
			&i.SchemaVersion,
			&i.Payload,
			&i.Origin,
			&i.CreatedBy,
			&i.ChangeReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRevisionNo = `-- name: NextRevisionNo :one
SELECT (COALESCE(MAX(revision_no), 0) + 1)::bigint AS next_no
FROM resource_revisions
WHERE resource_id = $1
`

func (q *Queries) NextRevisionNo(ctx context.Context, resourceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextRevisionNo, resourceID)
	var next_no int64
	err := row.Scan(&next_no)
	return next_no, err
}
