// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAlias = `-- name: DeleteAlias :exec
DELETE FROM tag_aliases
WHERE id = $1
`

func (q *Queries) DeleteAlias(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlias, id)
	return err
}

const demotePrimaryAliases = `-- name: DemotePrimaryAliases :exec
UPDATE tag_aliases
SET is_primary = false
WHERE tag_id = $1 AND is_primary
`

func (q *Queries) DemotePrimaryAliases(ctx context.Context, tagID uuid.UUID) error {
	_, err := q.db.Exec(ctx, demotePrimaryAliases, tagID)
	return err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id
FROM admin_users
WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTag = `-- name: GetTag :one
SELECT id, dimension, name, slug, status, merged_into_id
FROM tags
WHERE id = $1
`

type GetTagRow struct {
	ID           uuid.UUID
	Dimension    string
	Name         string
	Slug         string
	Status       string
	MergedIntoID pgtype.UUID
}

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (GetTagRow, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i GetTagRow
	err := row.Scan(
		&i.ID,
		&i.Dimension,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.MergedIntoID,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, dimension, name, slug, status, merged_into_id
FROM tags
WHERE dimension = $1 AND slug = $2
`

type GetTagBySlugParams struct {
	Dimension string
	Slug      string
}

type GetTagBySlugRow struct {
	ID           uuid.UUID
	Dimension    string
	Name         string
	Slug         string
	Status       string
	MergedIntoID pgtype.UUID
}

func (q *Queries) GetTagBySlug(ctx context.Context, arg GetTagBySlugParams) (GetTagBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, arg.Dimension, arg.Slug)
	var i GetTagBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Dimension,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.MergedIntoID,
	)
	return i, err
}

const insertAdminUser = `-- name: InsertAdminUser :exec
INSERT INTO admin_users (id, username, password_hash, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type InsertAdminUserParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Status       string
}

func (q *Queries) InsertAdminUser(ctx context.Context, arg InsertAdminUserParams) error {
	_, err := q.db.Exec(ctx, insertAdminUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Status,
	)
	return err
}

const insertAlias = `-- name: InsertAlias :exec
INSERT INTO tag_aliases (id, tag_id, dimension, alias, normalized_alias, is_primary, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAliasParams struct {
	ID              uuid.UUID
	TagID           uuid.UUID
	Dimension       string
	Alias           string
	NormalizedAlias string
	IsPrimary       bool
	CreatedAt       time.Time
}

func (q *Queries) InsertAlias(ctx context.Context, arg InsertAliasParams) error {
	_, err := q.db.Exec(ctx, insertAlias,
		arg.ID,
		arg.TagID,
		arg.Dimension,
		arg.Alias,
		arg.NormalizedAlias,
		arg.IsPrimary,
		arg.CreatedAt,
	)
	return err
}

const insertTag = `-- name: InsertTag :exec
INSERT INTO tags (id, dimension, name, slug, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'active', $5, $5)
`

type InsertTagParams struct {
	ID        uuid.UUID
	Dimension string
	Name      string
	Slug      string
	CreatedAt time.Time
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.Exec(ctx, insertTag,
		arg.ID,
		arg.Dimension,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	return err
}

const listAliases = `-- name: ListAliases :many
SELECT id, tag_id, dimension, alias, normalized_alias, is_primary
FROM tag_aliases
WHERE tag_id = $1
ORDER BY is_primary DESC, alias
`

type ListAliasesRow struct {
	ID              uuid.UUID
	TagID           uuid.UUID
	Dimension       string
	Alias           string
	NormalizedAlias string
	IsPrimary       bool
}

func (q *Queries) ListAliases(ctx context.Context, tagID uuid.UUID) ([]ListAliasesRow, error) {
	rows, err := q.db.Query(ctx, listAliases, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAliasesRow
	for rows.Next() {
		var i ListAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.TagID,
			&i.Dimension,
			&i.Alias,
			&i.NormalizedAlias,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAliasesByTags = `-- name: ListAliasesByTags :many
SELECT tag_id, alias, normalized_alias, is_primary
FROM tag_aliases
WHERE tag_id = ANY($1::uuid[])
`

type ListAliasesByTagsRow struct {
	TagID           uuid.UUID
	Alias           string
	NormalizedAlias string
	IsPrimary       bool
}

func (q *Queries) ListAliasesByTags(ctx context.Context, dollar_1 []uuid.UUID) ([]ListAliasesByTagsRow, error) {
	rows, err := q.db.Query(ctx, listAliasesByTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAliasesByTagsRow
	for rows.Next() {
		var i ListAliasesByTagsRow
		if err := rows.Scan(
			&i.TagID,
			&i.Alias,
			&i.NormalizedAlias,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, dimension, name, slug, status, merged_into_id
FROM tags
ORDER BY dimension, slug
`

type ListTagsRow struct {
	ID           uuid.UUID
	Dimension    string
	Name         string
	Slug         string
	Status       string
	MergedIntoID pgtype.UUID
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Dimension,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.MergedIntoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTags = `-- name: LockTags :many
SELECT id, dimension, name, slug, status, merged_into_id
FROM tags
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

type LockTagsRow struct {
	ID           uuid.UUID
	Dimension    string
	Name         string
	Slug         string
	Status       string
	MergedIntoID pgtype.UUID
}

func (q *Queries) LockTags(ctx context.Context, dollar_1 []uuid.UUID) ([]LockTagsRow, error) {
	rows, err := q.db.Query(ctx, lockTags, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockTagsRow
	for rows.Next() {
		var i LockTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Dimension,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.MergedIntoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTagMerged = `-- name: MarkTagMerged :execrows
UPDATE tags
SET status = 'merged',
    merged_into_id = $2,
    updated_at = $3
WHERE id = $1 AND status = 'active'
`

type MarkTagMergedParams struct {
	ID           uuid.UUID
	MergedIntoID pgtype.UUID
	UpdatedAt    time.Time
}

func (q *Queries) MarkTagMerged(ctx context.Context, arg MarkTagMergedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTagMerged, arg.ID, arg.MergedIntoID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveAlias = `-- name: MoveAlias :exec
UPDATE tag_aliases
SET tag_id = $2
WHERE id = $1
`

type MoveAliasParams struct {
	ID    uuid.UUID
	TagID uuid.UUID
}

func (q *Queries) MoveAlias(ctx context.Context, arg MoveAliasParams) error {
	_, err := q.db.Exec(ctx, moveAlias, arg.ID, arg.TagID)
	return err
}

const otherAliasExists = `-- name: OtherAliasExists :one
SELECT EXISTS (
    SELECT 1
    FROM tag_aliases
    WHERE dimension = $1 AND normalized_alias = $2 AND tag_id <> $3
) AS alias_exists
`

type OtherAliasExistsParams struct {
	Dimension       string
	NormalizedAlias string
	TagID           uuid.UUID
}

func (q *Queries) OtherAliasExists(ctx context.Context, arg OtherAliasExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, otherAliasExists, arg.Dimension, arg.NormalizedAlias, arg.TagID)
	var alias_exists bool
	err := row.Scan(&alias_exists)
	return alias_exists, err
}
