// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSession struct {
	ID             pgtype.UUID
	AdminID        pgtype.UUID
	TokenHash      string
	CsrfSecretHash string
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
}

type AdminUser struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	Status       string
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AssistantConversation struct {
	ID        pgtype.UUID
	AdminID   pgtype.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
}

type AssistantTurn struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	RequestKey     string
	UserText       string
	ProfileVersion string
	State          []byte
	Status         string
	Reply          string
	CreatedAt      pgtype.Timestamptz
}

type AuditLog struct {
	ID           int64
	ActorAdminID pgtype.UUID
	ActorType    string
	Action       string
	TargetType   string
	TargetID     string
	Changes      []byte
	RequestID    pgtype.Text
	JobID        pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type ChangeProposal struct {
	ID                pgtype.UUID
	ProcessingRunID   pgtype.UUID
	ProposalNo        int32
	ResourceID        pgtype.UUID
	BaseEditVersion   pgtype.Int8
	ProposedKind      string
	ProposedPayload   []byte
	FieldChanges      []byte
	Status            string
	ReviewedBy        pgtype.UUID
	ReviewDecisions   []byte
	ReviewedAt        pgtype.Timestamptz
	AppliedResourceID pgtype.UUID
	AppliedRevisionID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type ExternalMetricSnapshot struct {
	ID         int64
	ResourceID pgtype.UUID
	SourceID   pgtype.UUID
	ObservedAt pgtype.Timestamptz
	Stars      pgtype.Int8
	Forks      pgtype.Int8
	OpenIssues pgtype.Int8
	Extra      []byte
	CreatedAt  pgtype.Timestamptz
}

type FeaturedSlot struct {
	ID         pgtype.UUID
	Kind       string
	Placement  string
	Position   int32
	ResourceID pgtype.UUID
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
	Enabled    bool
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type IdempotencyRequest struct {
	ID             pgtype.UUID
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	Status         string
	ResponseStatus pgtype.Int2
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	ParentID       pgtype.UUID
	ItemIndex      pgtype.Int4
	RequestMeta    []byte
}

type IngestCredential struct {
	ID         pgtype.UUID
	SourceID   pgtype.UUID
	Name       string
	TokenHash  string
	Scopes     []string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	LastUsedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type InteractionEvent struct {
	ID          pgtype.UUID
	ResourceID  pgtype.UUID
	EventType   string
	VisitorHash string
	BucketStart pgtype.Timestamptz
	AcceptedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type McpAction struct {
	ID             pgtype.UUID
	AdminID        pgtype.UUID
	ConversationID pgtype.UUID
	RequestKey     string
	Operation      string
	Arguments      []byte
	Preview        []byte
	Status         string
	Result         []byte
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type McpToken struct {
	ID         pgtype.UUID
	AdminID    pgtype.UUID
	Name       string
	TokenHash  string
	CanPrepare bool
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CanExecute bool
}

type ProcessingRun struct {
	ID            pgtype.UUID
	RawRevisionID pgtype.UUID
	Stage         string
	PipelineKey   string
	PipelinePlan  []byte
	InputHash     string
	RuleVersion   string
	RerunNo       int32
	RunKey        string
	Status        string
	Output        []byte
	AttemptCount  int32
	LeaseUntil    pgtype.Timestamptz
	RiverJobID    pgtype.Int8
	ErrorCode     pgtype.Text
	ErrorMessage  pgtype.Text
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ProviderBudgetReservation struct {
	ProviderCallID pgtype.UUID
	BudgetWindowID pgtype.UUID
	ReservedAmount pgtype.Numeric
	SettledAmount  pgtype.Numeric
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ProviderBudgetWindow struct {
	ID             pgtype.UUID
	ScopeKey       string
	Currency       string
	WindowStart    pgtype.Timestamptz
	WindowEnd      pgtype.Timestamptz
	LimitAmount    pgtype.Numeric
	ReservedAmount pgtype.Numeric
	SpentAmount    pgtype.Numeric
	UpdatedAt      pgtype.Timestamptz
}

type ProviderCall struct {
	ID                pgtype.UUID
	ProcessingRunID   pgtype.UUID
	SourceRunID       pgtype.UUID
	ProviderKey       string
	Model             pgtype.Text
	ProfileVersion    pgtype.Text
	RequestKey        string
	AttemptNo         int32
	Status            string
	ProviderRequestID pgtype.Text
	ResponsePayload   []byte
	InputTokens       pgtype.Int8
	OutputTokens      pgtype.Int8
	Currency          string
	ReservedCost      pgtype.Numeric
	ActualCost        pgtype.Numeric
	ErrorCode         pgtype.Text
	CreatedAt         pgtype.Timestamptz
	SentAt            pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	PreviewRequestKey pgtype.Text
	RequestSummary    []byte
	AssistantTurnID   pgtype.UUID
}

type RankingEntry struct {
	RunID                  pgtype.UUID
	ResourceID             pgtype.UUID
	Kind                   string
	QualityScore           pgtype.Numeric
	HeatScore              pgtype.Numeric
	FreshnessScore         pgtype.Numeric
	RecommendationScore    pgtype.Numeric
	HeatPosition           int32
	RecommendationPosition int32
	ReasonCode             pgtype.Text
}

type RankingRun struct {
	ID          pgtype.UUID
	Kind        string
	RuleVersion string
	Parameters  []byte
	Status      string
	IsCurrent   bool
	ComputedAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	ErrorCode   pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type RawItem struct {
	ID                pgtype.UUID
	OwnerSourceID     pgtype.UUID
	IdentityKey       string
	CanonicalUrl      pgtype.Text
	CurrentRevisionID pgtype.UUID
	IsBackfill        bool
	FirstDiscoveredAt pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
}

type RawItemDiscovery struct {
	ID            pgtype.UUID
	RawItemID     pgtype.UUID
	SourceID      pgtype.UUID
	SourceItemKey string
	ObservedUrl   pgtype.Text
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	SeenCount     int64
}

type RawItemRevision struct {
	ID                   pgtype.UUID
	RawItemID            pgtype.UUID
	RevisionNo           int64
	ContentHash          string
	NormalizationVersion string
	Title                string
	Excerpt              pgtype.Text
	BodyText             pgtype.Text
	BodyHtml             pgtype.Text
	Author               pgtype.Text
	Language             pgtype.Text
	SourcePublishedAt    pgtype.Timestamptz
	SourceUpdatedAt      pgtype.Timestamptz
	RawPayload           []byte
	FetchedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
}

type Resource struct {
	ID                pgtype.UUID
	Kind              string
	IdentityKey       pgtype.Text
	Slug              string
	Status            string
	DraftRevisionID   pgtype.UUID
	EditVersion       int64
	FieldLocks        []string
	IsDemo            bool
	FreshnessEligible bool
	FirstPublishedAt  pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	LastCheckedAt     pgtype.Timestamptz
}

type ResourceEvidence struct {
	ID                 pgtype.UUID
	ResourceID         pgtype.UUID
	ResourceRevisionID pgtype.UUID
	ProposalID         pgtype.UUID
	RawRevisionID      pgtype.UUID
	FieldPath          string
	EvidenceExcerpt    pgtype.Text
	Locator            []byte
	CreatedAt          pgtype.Timestamptz
}

type ResourceMetricsDaily struct {
	ResourceID     pgtype.UUID
	MetricDate     pgtype.Date
	DetailViews    int64
	OutboundClicks int64
	UpdatedAt      pgtype.Timestamptz
}

type ResourcePublication struct {
	ResourceID           pgtype.UUID
	RevisionID           pgtype.UUID
	Kind                 string
	Title                string
	Aliases              []string
	Summary              string
	BodyMarkdown         pgtype.Text
	CoverUrls            []string
	PrimaryCategoryID    pgtype.UUID
	QualityScore         int16
	RecommendationReason pgtype.Text
	Details              []byte
	SearchText           string
	ContentUpdatedAt     pgtype.Timestamptz
	ProjectedAt          pgtype.Timestamptz
}

type ResourceRevision struct {
	ID            pgtype.UUID
	ResourceID    pgtype.UUID
	RevisionNo    int64
	SchemaVersion int32
	Payload       []byte
	Origin        string
	CreatedBy     pgtype.UUID
	ChangeReason  string
	CreatedAt     pgtype.Timestamptz
}

type ResourceTag struct {
	ResourceID pgtype.UUID
	TagID      pgtype.UUID
	AssignedBy string
	CreatedAt  pgtype.Timestamptz
}

type Source struct {
	ID                pgtype.UUID
	SourceKey         string
	Name              string
	Kind              string
	ParticipationMode string
	TrustTier         string
	Config            []byte
	CredentialRef     pgtype.Text
	Enabled           bool
	IntervalSeconds   int32
	Checkpoint        []byte
	NextFetchAt       pgtype.Timestamptz
	LastSuccessAt     pgtype.Timestamptz
	FailureCount      int32
	AutoUpdateFields  []string
	AllowFulltext     bool
	EditVersion       int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type SourceRun struct {
	ID                pgtype.UUID
	SourceID          pgtype.UUID
	SourceEditVersion int64
	ScheduledFor      pgtype.Timestamptz
	RunKey            string
	Status            string
	CheckpointBefore  []byte
	CheckpointAfter   []byte
	Stats             []byte
	ErrorCode         pgtype.Text
	ErrorMessage      pgtype.Text
	RiverJobID        pgtype.Int8
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type Tag struct {
	ID           pgtype.UUID
	Dimension    string
	Name         string
	Slug         string
	Status       string
	MergedIntoID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type TagAlias struct {
	ID              pgtype.UUID
	TagID           pgtype.UUID
	Dimension       string
	Alias           string
	NormalizedAlias string
	IsPrimary       bool
	CreatedAt       pgtype.Timestamptz
}
