// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminExists = `-- name: AdminExists :one
SELECT id
FROM admin_users
WHERE id = $1
  AND status = 'active'
`

func (q *Queries) AdminExists(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, adminExists, id)
	err := row.Scan(&id)
	return id, err
}

const findCredentialByHash = `-- name: FindCredentialByHash :one
SELECT c.id, c.source_id, c.name, c.token_hash, c.scopes, c.expires_at, c.revoked_at, c.created_by,
       s.source_key, s.enabled, s.trust_tier, s.edit_version, s.participation_mode, s.kind
FROM ingest_credentials c
JOIN sources s ON s.id = c.source_id
WHERE c.token_hash = $1
`

type FindCredentialByHashRow struct {
	ID                uuid.UUID
	SourceID          uuid.UUID
	Name              string
	TokenHash         string
	Scopes            []string
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedBy         uuid.UUID
	SourceKey         string
	Enabled           bool
	TrustTier         string
	EditVersion       int64
	ParticipationMode string
	Kind              string
}

func (q *Queries) FindCredentialByHash(ctx context.Context, tokenHash string) (FindCredentialByHashRow, error) {
	row := q.db.QueryRow(ctx, findCredentialByHash, tokenHash)
	var i FindCredentialByHashRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.SourceKey,
		&i.Enabled,
		&i.TrustTier,
		&i.EditVersion,
		&i.ParticipationMode,
		&i.Kind,
	)
	return i, err
}

const insertCredential = `-- name: InsertCredential :one
INSERT INTO ingest_credentials (
    id, source_id, name, token_hash, scopes, created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id
`

type InsertCredentialParams struct {
	ID        uuid.UUID
	SourceID  uuid.UUID
	Name      string
	TokenHash string
	Scopes    []string
	CreatedBy uuid.UUID
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCredential,
		arg.ID,
		arg.SourceID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const touchCredentialUsed = `-- name: TouchCredentialUsed :exec
UPDATE ingest_credentials
SET last_used_at = $1
WHERE id = $2
`

type TouchCredentialUsedParams struct {
	LastUsedAt pgtype.Timestamptz
	ID         uuid.UUID
}

func (q *Queries) TouchCredentialUsed(ctx context.Context, arg TouchCredentialUsedParams) error {
	_, err := q.db.Exec(ctx, touchCredentialUsed, arg.LastUsedAt, arg.ID)
	return err
}
