// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeIngestRequest = `-- name: CompleteIngestRequest :execrows
UPDATE idempotency_requests
SET status = 'completed',
    response_status = $1,
    response_body = $2,
    expires_at = $3
WHERE id = $4
  AND principal_key = $5
  AND status = 'processing'
`

type CompleteIngestRequestParams struct {
	ResponseStatus *int16
	ResponseBody   []byte
	ExpiresAt      time.Time
	ID             uuid.UUID
	PrincipalKey   string
}

func (q *Queries) CompleteIngestRequest(ctx context.Context, arg CompleteIngestRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIngestRequest,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ExpiresAt,
		arg.ID,
		arg.PrincipalKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIngestBatch = `-- name: GetIngestBatch :one
SELECT id, principal_key, scope, idempotency_key, request_hash, status, response_status, response_body,
       request_meta, expires_at
FROM idempotency_requests
WHERE principal_key = $1
  AND scope = 'ingest.batch.v1'
  AND idempotency_key = $2
  AND parent_id IS NULL
`

type GetIngestBatchParams struct {
	PrincipalKey   string
	IdempotencyKey string
}

type GetIngestBatchRow struct {
	ID             uuid.UUID
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	Status         string
	ResponseStatus *int16
	ResponseBody   []byte
	RequestMeta    json.RawMessage
	ExpiresAt      time.Time
}

func (q *Queries) GetIngestBatch(ctx context.Context, arg GetIngestBatchParams) (GetIngestBatchRow, error) {
	row := q.db.QueryRow(ctx, getIngestBatch, arg.PrincipalKey, arg.IdempotencyKey)
	var i GetIngestBatchRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalKey,
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.RequestMeta,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIngestBatch = `-- name: InsertIngestBatch :one
INSERT INTO idempotency_requests (
    id, principal_key, scope, idempotency_key, request_hash, status, expires_at, request_meta
) VALUES (
    $1, $2, 'ingest.batch.v1', $3,
    $4, 'processing', $5, $6
)
ON CONFLICT (principal_key, scope, idempotency_key) DO NOTHING
RETURNING id, principal_key, scope, idempotency_key, request_hash, status, response_status, response_body,
          request_meta, expires_at
`

type InsertIngestBatchParams struct {
	ID             uuid.UUID
	PrincipalKey   string
	IdempotencyKey string
	RequestHash    string
	ExpiresAt      time.Time
	RequestMeta    json.RawMessage
}

type InsertIngestBatchRow struct {
	ID             uuid.UUID
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	Status         string
	ResponseStatus *int16
	ResponseBody   []byte
	RequestMeta    json.RawMessage
	ExpiresAt      time.Time
}

func (q *Queries) InsertIngestBatch(ctx context.Context, arg InsertIngestBatchParams) (InsertIngestBatchRow, error) {
	row := q.db.QueryRow(ctx, insertIngestBatch,
		arg.ID,
		arg.PrincipalKey,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.RequestMeta,
	)
	var i InsertIngestBatchRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalKey,
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.RequestMeta,
		&i.ExpiresAt,
	)
	return i, err
}

const insertIngestChild = `-- name: InsertIngestChild :one
INSERT INTO idempotency_requests (
    id, principal_key, scope, idempotency_key, request_hash, status, expires_at,
    parent_id, item_index, request_meta
) VALUES (
    $1, $2, $3, $4,
    $5, 'processing', $6,
    $7, $8, '{}'::jsonb
)
ON CONFLICT DO NOTHING
RETURNING id, status, request_hash, response_status, response_body, item_index
`

type InsertIngestChildParams struct {
	ID             uuid.UUID
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	ExpiresAt      time.Time
	ParentID       pgtype.UUID
	ItemIndex      *int32
}

type InsertIngestChildRow struct {
	ID             uuid.UUID
	Status         string
	RequestHash    string
	ResponseStatus *int16
	ResponseBody   []byte
	ItemIndex      *int32
}

func (q *Queries) InsertIngestChild(ctx context.Context, arg InsertIngestChildParams) (InsertIngestChildRow, error) {
	row := q.db.QueryRow(ctx, insertIngestChild,
		arg.ID,
		arg.PrincipalKey,
		arg.Scope,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpiresAt,
		arg.ParentID,
		arg.ItemIndex,
	)
	var i InsertIngestChildRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ItemIndex,
	)
	return i, err
}

const listIngestChildren = `-- name: ListIngestChildren :many
SELECT item_index, status, response_status, response_body
FROM idempotency_requests
WHERE parent_id = $1
  AND principal_key = $2
ORDER BY item_index
`

type ListIngestChildrenParams struct {
	ParentID     pgtype.UUID
	PrincipalKey string
}

type ListIngestChildrenRow struct {
	ItemIndex      *int32
	Status         string
	ResponseStatus *int16
	ResponseBody   []byte
}

func (q *Queries) ListIngestChildren(ctx context.Context, arg ListIngestChildrenParams) ([]ListIngestChildrenRow, error) {
	rows, err := q.db.Query(ctx, listIngestChildren, arg.ParentID, arg.PrincipalKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngestChildrenRow
	for rows.Next() {
		var i ListIngestChildrenRow
		if err := rows.Scan(
			&i.ItemIndex,
			&i.Status,
			&i.ResponseStatus,
			&i.ResponseBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIngestChild = `-- name: LockIngestChild :one
SELECT id, status, request_hash, response_status, response_body, item_index
FROM idempotency_requests
WHERE principal_key = $1
  AND scope = $2
  AND idempotency_key = $3
FOR UPDATE
`

type LockIngestChildParams struct {
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
}

type LockIngestChildRow struct {
	ID             uuid.UUID
	Status         string
	RequestHash    string
	ResponseStatus *int16
	ResponseBody   []byte
	ItemIndex      *int32
}

func (q *Queries) LockIngestChild(ctx context.Context, arg LockIngestChildParams) (LockIngestChildRow, error) {
	row := q.db.QueryRow(ctx, lockIngestChild, arg.PrincipalKey, arg.Scope, arg.IdempotencyKey)
	var i LockIngestChildRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ItemIndex,
	)
	return i, err
}

const lockIngestParentShare = `-- name: LockIngestParentShare :one
SELECT id, principal_key, scope, idempotency_key, request_hash, status, response_status, response_body,
       request_meta
FROM idempotency_requests
WHERE id = $1
  AND principal_key = $2
FOR SHARE
`

type LockIngestParentShareParams struct {
	ID           uuid.UUID
	PrincipalKey string
}

type LockIngestParentShareRow struct {
	ID             uuid.UUID
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	Status         string
	ResponseStatus *int16
	ResponseBody   []byte
	RequestMeta    json.RawMessage
}

func (q *Queries) LockIngestParentShare(ctx context.Context, arg LockIngestParentShareParams) (LockIngestParentShareRow, error) {
	row := q.db.QueryRow(ctx, lockIngestParentShare, arg.ID, arg.PrincipalKey)
	var i LockIngestParentShareRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalKey,
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.RequestMeta,
	)
	return i, err
}

const lockIngestParentUpdate = `-- name: LockIngestParentUpdate :one
SELECT id, principal_key, scope, idempotency_key, request_hash, status, response_status, response_body,
       request_meta
FROM idempotency_requests
WHERE id = $1
  AND principal_key = $2
FOR UPDATE
`

type LockIngestParentUpdateParams struct {
	ID           uuid.UUID
	PrincipalKey string
}

type LockIngestParentUpdateRow struct {
	ID             uuid.UUID
	PrincipalKey   string
	Scope          string
	IdempotencyKey string
	RequestHash    string
	Status         string
	ResponseStatus *int16
	ResponseBody   []byte
	RequestMeta    json.RawMessage
}

func (q *Queries) LockIngestParentUpdate(ctx context.Context, arg LockIngestParentUpdateParams) (LockIngestParentUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockIngestParentUpdate, arg.ID, arg.PrincipalKey)
	var i LockIngestParentUpdateRow
	err := row.Scan(
		&i.ID,
		&i.PrincipalKey,
		&i.Scope,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.RequestMeta,
	)
	return i, err
}
