// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const discoveryContentHash = `-- name: DiscoveryContentHash :one
SELECT rev.content_hash
FROM raw_item_discoveries d
JOIN raw_items item ON item.id = d.raw_item_id
JOIN raw_item_revisions rev ON rev.id = item.current_revision_id
WHERE d.source_id = $1
  AND d.source_item_key = $2
`

type DiscoveryContentHashParams struct {
	SourceID      uuid.UUID
	SourceItemKey string
}

func (q *Queries) DiscoveryContentHash(ctx context.Context, arg DiscoveryContentHashParams) (string, error) {
	row := q.db.QueryRow(ctx, discoveryContentHash, arg.SourceID, arg.SourceItemKey)
	var content_hash string
	err := row.Scan(&content_hash)
	return content_hash, err
}

const getRawRevision = `-- name: GetRawRevision :one
SELECT id, raw_item_id, revision_no, content_hash, normalization_version, title, excerpt, body_text,
       body_html, author, language, source_published_at, source_updated_at, raw_payload, fetched_at
FROM raw_item_revisions
WHERE id = $1
`

type GetRawRevisionRow struct {
	ID                   uuid.UUID
	RawItemID            uuid.UUID
	RevisionNo           int64
	ContentHash          string
	NormalizationVersion string
	Title                string
	Excerpt              *string
	BodyText             *string
	BodyHtml             *string
	Author               *string
	Language             *string
	SourcePublishedAt    pgtype.Timestamptz
	SourceUpdatedAt      pgtype.Timestamptz
	RawPayload           json.RawMessage
	FetchedAt            time.Time
}

func (q *Queries) GetRawRevision(ctx context.Context, id uuid.UUID) (GetRawRevisionRow, error) {
	row := q.db.QueryRow(ctx, getRawRevision, id)
	var i GetRawRevisionRow
	err := row.Scan(
		&i.ID,
		&i.RawItemID,
		&i.RevisionNo,
		&i.ContentHash,
		&i.NormalizationVersion,
		&i.Title,
		&i.Excerpt,
		&i.BodyText,
		&i.BodyHtml,
		&i.Author,
		&i.Language,
		&i.SourcePublishedAt,
		&i.SourceUpdatedAt,
		&i.RawPayload,
		&i.FetchedAt,
	)
	return i, err
}

const insertRawItem = `-- name: InsertRawItem :one
INSERT INTO raw_items (
    id, owner_source_id, identity_key, canonical_url, is_backfill, first_discovered_at, last_seen_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7
)
ON CONFLICT (identity_key) DO NOTHING
RETURNING id, owner_source_id, identity_key, canonical_url, current_revision_id, is_backfill,
          first_discovered_at, last_seen_at
`

type InsertRawItemParams struct {
	ID                uuid.UUID
	OwnerSourceID     uuid.UUID
	IdentityKey       string
	CanonicalUrl      *string
	IsBackfill        bool
	FirstDiscoveredAt time.Time
	LastSeenAt        time.Time
}

func (q *Queries) InsertRawItem(ctx context.Context, arg InsertRawItemParams) (RawItem, error) {
	row := q.db.QueryRow(ctx, insertRawItem,
		arg.ID,
		arg.OwnerSourceID,
		arg.IdentityKey,
		arg.CanonicalUrl,
		arg.IsBackfill,
		arg.FirstDiscoveredAt,
		arg.LastSeenAt,
	)
	var i RawItem
	err := row.Scan(
		&i.ID,
		&i.OwnerSourceID,
		&i.IdentityKey,
		&i.CanonicalUrl,
		&i.CurrentRevisionID,
		&i.IsBackfill,
		&i.FirstDiscoveredAt,
		&i.LastSeenAt,
	)
	return i, err
}

const insertRawRevision = `-- name: InsertRawRevision :one
INSERT INTO raw_item_revisions (
    id, raw_item_id, revision_no, content_hash, normalization_version, title, excerpt, body_text,
    body_html, author, language, source_published_at, source_updated_at, raw_payload, fetched_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15
)
RETURNING id, revision_no
`

type InsertRawRevisionParams struct {
	ID                   uuid.UUID
	RawItemID            uuid.UUID
	RevisionNo           int64
	ContentHash          string
	NormalizationVersion string
	Title                string
	Excerpt              *string
	BodyText             *string
	BodyHtml             *string
	Author               *string
	Language             *string
	SourcePublishedAt    pgtype.Timestamptz
	SourceUpdatedAt      pgtype.Timestamptz
	RawPayload           json.RawMessage
	FetchedAt            time.Time
}

type InsertRawRevisionRow struct {
	ID         uuid.UUID
	RevisionNo int64
}

func (q *Queries) InsertRawRevision(ctx context.Context, arg InsertRawRevisionParams) (InsertRawRevisionRow, error) {
	row := q.db.QueryRow(ctx, insertRawRevision,
		arg.ID,
		arg.RawItemID,
		arg.RevisionNo,
		arg.ContentHash,
		arg.NormalizationVersion,
		arg.Title,
		arg.Excerpt,
		arg.BodyText,
		arg.BodyHtml,
		arg.Author,
		arg.Language,
		arg.SourcePublishedAt,
		arg.SourceUpdatedAt,
		arg.RawPayload,
		arg.FetchedAt,
	)
	var i InsertRawRevisionRow
	err := row.Scan(&i.ID, &i.RevisionNo)
	return i, err
}

const lockRawItemByIdentity = `-- name: LockRawItemByIdentity :one
SELECT id, owner_source_id, identity_key, canonical_url, current_revision_id, is_backfill,
       first_discovered_at, last_seen_at
FROM raw_items
WHERE identity_key = $1
FOR UPDATE
`

func (q *Queries) LockRawItemByIdentity(ctx context.Context, identityKey string) (RawItem, error) {
	row := q.db.QueryRow(ctx, lockRawItemByIdentity, identityKey)
	var i RawItem
	err := row.Scan(
		&i.ID,
		&i.OwnerSourceID,
		&i.IdentityKey,
		&i.CanonicalUrl,
		&i.CurrentRevisionID,
		&i.IsBackfill,
		&i.FirstDiscoveredAt,
		&i.LastSeenAt,
	)
	return i, err
}

const nextRevisionNo = `-- name: NextRevisionNo :one
SELECT (COALESCE(MAX(revision_no), 0) + 1)::bigint AS revision_no
FROM raw_item_revisions
WHERE raw_item_id = $1
`

func (q *Queries) NextRevisionNo(ctx context.Context, rawItemID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextRevisionNo, rawItemID)
	var revision_no int64
	err := row.Scan(&revision_no)
	return revision_no, err
}

const setCurrentRevision = `-- name: SetCurrentRevision :exec
UPDATE raw_items
SET current_revision_id = $1,
    last_seen_at = $2,
    canonical_url = COALESCE($3, canonical_url)
WHERE id = $4
`

type SetCurrentRevisionParams struct {
	CurrentRevisionID pgtype.UUID
	LastSeenAt        time.Time
	CanonicalUrl      *string
	ID                uuid.UUID
}

func (q *Queries) SetCurrentRevision(ctx context.Context, arg SetCurrentRevisionParams) error {
	_, err := q.db.Exec(ctx, setCurrentRevision,
		arg.CurrentRevisionID,
		arg.LastSeenAt,
		arg.CanonicalUrl,
		arg.ID,
	)
	return err
}

const touchRawItem = `-- name: TouchRawItem :exec
UPDATE raw_items
SET last_seen_at = $1,
    canonical_url = COALESCE($2, canonical_url)
WHERE id = $3
`

type TouchRawItemParams struct {
	LastSeenAt   time.Time
	CanonicalUrl *string
	ID           uuid.UUID
}

func (q *Queries) TouchRawItem(ctx context.Context, arg TouchRawItemParams) error {
	_, err := q.db.Exec(ctx, touchRawItem, arg.LastSeenAt, arg.CanonicalUrl, arg.ID)
	return err
}

const upsertDiscovery = `-- name: UpsertDiscovery :one
INSERT INTO raw_item_discoveries (
    id, raw_item_id, source_id, source_item_key, observed_url, first_seen_at, last_seen_at, seen_count
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $6, 1
)
ON CONFLICT (source_id, source_item_key) DO UPDATE
SET raw_item_id = EXCLUDED.raw_item_id,
    observed_url = COALESCE(EXCLUDED.observed_url, raw_item_discoveries.observed_url),
    last_seen_at = EXCLUDED.last_seen_at,
    seen_count = raw_item_discoveries.seen_count + 1
RETURNING id, raw_item_id, seen_count
`

type UpsertDiscoveryParams struct {
	ID            uuid.UUID
	RawItemID     uuid.UUID
	SourceID      uuid.UUID
	SourceItemKey string
	ObservedUrl   *string
	SeenAt        time.Time
}

type UpsertDiscoveryRow struct {
	ID        uuid.UUID
	RawItemID uuid.UUID
	SeenCount int64
}

func (q *Queries) UpsertDiscovery(ctx context.Context, arg UpsertDiscoveryParams) (UpsertDiscoveryRow, error) {
	row := q.db.QueryRow(ctx, upsertDiscovery,
		arg.ID,
		arg.RawItemID,
		arg.SourceID,
		arg.SourceItemKey,
		arg.ObservedUrl,
		arg.SeenAt,
	)
	var i UpsertDiscoveryRow
	err := row.Scan(&i.ID, &i.RawItemID, &i.SeenCount)
	return i, err
}
