// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertMetricSnapshot = `-- name: InsertMetricSnapshot :exec
INSERT INTO external_metric_snapshots (
    resource_id, source_id, observed_at, stars, forks, open_issues, extra
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
ON CONFLICT (resource_id, source_id, observed_at) DO NOTHING
`

type InsertMetricSnapshotParams struct {
	ResourceID uuid.UUID
	SourceID   uuid.UUID
	ObservedAt time.Time
	Stars      *int64
	Forks      *int64
	OpenIssues *int64
	Extra      json.RawMessage
}

func (q *Queries) InsertMetricSnapshot(ctx context.Context, arg InsertMetricSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertMetricSnapshot,
		arg.ResourceID,
		arg.SourceID,
		arg.ObservedAt,
		arg.Stars,
		arg.Forks,
		arg.OpenIssues,
		arg.Extra,
	)
	return err
}
