// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const finishSourceRun = `-- name: FinishSourceRun :execrows
UPDATE source_runs
SET status = $1,
    checkpoint_after = $2,
    stats = $3,
    error_code = $4,
    error_message = $5,
    finished_at = $6
WHERE id = $7
  AND status IN ('pending', 'running')
`

type FinishSourceRunParams struct {
	Status          string
	CheckpointAfter json.RawMessage
	Stats           json.RawMessage
	ErrorCode       *string
	ErrorMessage    *string
	FinishedAt      pgtype.Timestamptz
	ID              uuid.UUID
}

func (q *Queries) FinishSourceRun(ctx context.Context, arg FinishSourceRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishSourceRun,
		arg.Status,
		arg.CheckpointAfter,
		arg.Stats,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSourceRun = `-- name: GetSourceRun :one
SELECT id, source_id, source_edit_version, scheduled_for, run_key, status,
       checkpoint_before, checkpoint_after, stats, error_code, error_message, river_job_id,
       started_at, finished_at
FROM source_runs
WHERE id = $1
`

type GetSourceRunRow struct {
	ID                uuid.UUID
	SourceID          uuid.UUID
	SourceEditVersion int64
	ScheduledFor      time.Time
	RunKey            string
	Status            string
	CheckpointBefore  json.RawMessage
	CheckpointAfter   json.RawMessage
	Stats             json.RawMessage
	ErrorCode         *string
	ErrorMessage      *string
	RiverJobID        *int64
	StartedAt         pgtype.Timestamptz
	FinishedAt        pgtype.Timestamptz
}

func (q *Queries) GetSourceRun(ctx context.Context, id uuid.UUID) (GetSourceRunRow, error) {
	row := q.db.QueryRow(ctx, getSourceRun, id)
	var i GetSourceRunRow
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.SourceEditVersion,
		&i.ScheduledFor,
		&i.RunKey,
		&i.Status,
		&i.CheckpointBefore,
		&i.CheckpointAfter,
		&i.Stats,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.RiverJobID,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertSourceRun = `-- name: InsertSourceRun :one
INSERT INTO source_runs (
    id, source_id, source_edit_version, scheduled_for, run_key, status, checkpoint_before
) VALUES (
    $1, $2, $3,
    $4, $5, 'pending', $6
)
ON CONFLICT (run_key) DO NOTHING
RETURNING id
`

type InsertSourceRunParams struct {
	ID                uuid.UUID
	SourceID          uuid.UUID
	SourceEditVersion int64
	ScheduledFor      time.Time
	RunKey            string
	CheckpointBefore  json.RawMessage
}

func (q *Queries) InsertSourceRun(ctx context.Context, arg InsertSourceRunParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSourceRun,
		arg.ID,
		arg.SourceID,
		arg.SourceEditVersion,
		arg.ScheduledFor,
		arg.RunKey,
		arg.CheckpointBefore,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markSourceRunRunning = `-- name: MarkSourceRunRunning :exec
UPDATE source_runs
SET status = 'running',
    started_at = COALESCE(started_at, $1)
WHERE id = $2
  AND status IN ('pending', 'running')
`

type MarkSourceRunRunningParams struct {
	StartedAt pgtype.Timestamptz
	ID        uuid.UUID
}

func (q *Queries) MarkSourceRunRunning(ctx context.Context, arg MarkSourceRunRunningParams) error {
	_, err := q.db.Exec(ctx, markSourceRunRunning, arg.StartedAt, arg.ID)
	return err
}

const setSourceRunJob = `-- name: SetSourceRunJob :exec
UPDATE source_runs
SET river_job_id = $1
WHERE id = $2
`

type SetSourceRunJobParams struct {
	RiverJobID *int64
	ID         uuid.UUID
}

func (q *Queries) SetSourceRunJob(ctx context.Context, arg SetSourceRunJobParams) error {
	_, err := q.db.Exec(ctx, setSourceRunJob, arg.RiverJobID, arg.ID)
	return err
}
