// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpSourceFailure = `-- name: BumpSourceFailure :exec
UPDATE sources
SET failure_count = failure_count + 1,
    updated_at = $1
WHERE id = $2
`

type BumpSourceFailureParams struct {
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) BumpSourceFailure(ctx context.Context, arg BumpSourceFailureParams) error {
	_, err := q.db.Exec(ctx, bumpSourceFailure, arg.UpdatedAt, arg.ID)
	return err
}

const getSourceByKey = `-- name: GetSourceByKey :one
SELECT id, source_key, name, kind, participation_mode, trust_tier, config, credential_ref,
       enabled, interval_seconds, checkpoint, next_fetch_at, last_success_at, failure_count,
       auto_update_fields, allow_fulltext, edit_version
FROM sources
WHERE source_key = $1
`

type GetSourceByKeyRow struct {
	ID                uuid.UUID
	SourceKey         string
	Name              string
	Kind              string
	ParticipationMode string
	TrustTier         string
	Config            json.RawMessage
	CredentialRef     *string
	Enabled           bool
	IntervalSeconds   int32
	Checkpoint        json.RawMessage
	NextFetchAt       pgtype.Timestamptz
	LastSuccessAt     pgtype.Timestamptz
	FailureCount      int32
	AutoUpdateFields  []string
	AllowFulltext     bool
	EditVersion       int64
}

func (q *Queries) GetSourceByKey(ctx context.Context, sourceKey string) (GetSourceByKeyRow, error) {
	row := q.db.QueryRow(ctx, getSourceByKey, sourceKey)
	var i GetSourceByKeyRow
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Kind,
		&i.ParticipationMode,
		&i.TrustTier,
		&i.Config,
		&i.CredentialRef,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.Checkpoint,
		&i.NextFetchAt,
		&i.LastSuccessAt,
		&i.FailureCount,
		&i.AutoUpdateFields,
		&i.AllowFulltext,
		&i.EditVersion,
	)
	return i, err
}

const lockDueSource = `-- name: LockDueSource :one
SELECT s.id, s.source_key, s.name, s.kind, s.participation_mode, s.trust_tier, s.config, s.credential_ref,
       s.enabled, s.interval_seconds, s.checkpoint, s.next_fetch_at, s.last_success_at, s.failure_count,
       s.auto_update_fields, s.allow_fulltext, s.edit_version
FROM sources s
WHERE s.enabled
  AND s.trust_tier <> 'excluded'
  AND s.next_fetch_at IS NOT NULL
  AND s.next_fetch_at <= $1
  AND NOT EXISTS (
      SELECT 1 FROM source_runs r
      WHERE r.source_id = s.id AND r.status IN ('pending', 'running')
  )
ORDER BY s.next_fetch_at, s.id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

type LockDueSourceRow struct {
	ID                uuid.UUID
	SourceKey         string
	Name              string
	Kind              string
	ParticipationMode string
	TrustTier         string
	Config            json.RawMessage
	CredentialRef     *string
	Enabled           bool
	IntervalSeconds   int32
	Checkpoint        json.RawMessage
	NextFetchAt       pgtype.Timestamptz
	LastSuccessAt     pgtype.Timestamptz
	FailureCount      int32
	AutoUpdateFields  []string
	AllowFulltext     bool
	EditVersion       int64
}

func (q *Queries) LockDueSource(ctx context.Context, now pgtype.Timestamptz) (LockDueSourceRow, error) {
	row := q.db.QueryRow(ctx, lockDueSource, now)
	var i LockDueSourceRow
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Kind,
		&i.ParticipationMode,
		&i.TrustTier,
		&i.Config,
		&i.CredentialRef,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.Checkpoint,
		&i.NextFetchAt,
		&i.LastSuccessAt,
		&i.FailureCount,
		&i.AutoUpdateFields,
		&i.AllowFulltext,
		&i.EditVersion,
	)
	return i, err
}

const lockSource = `-- name: LockSource :one
SELECT id, source_key, name, kind, participation_mode, trust_tier, config, credential_ref,
       enabled, interval_seconds, checkpoint, next_fetch_at, last_success_at, failure_count,
       auto_update_fields, allow_fulltext, edit_version
FROM sources
WHERE id = $1
FOR UPDATE
`

type LockSourceRow struct {
	ID                uuid.UUID
	SourceKey         string
	Name              string
	Kind              string
	ParticipationMode string
	TrustTier         string
	Config            json.RawMessage
	CredentialRef     *string
	Enabled           bool
	IntervalSeconds   int32
	Checkpoint        json.RawMessage
	NextFetchAt       pgtype.Timestamptz
	LastSuccessAt     pgtype.Timestamptz
	FailureCount      int32
	AutoUpdateFields  []string
	AllowFulltext     bool
	EditVersion       int64
}

func (q *Queries) LockSource(ctx context.Context, id uuid.UUID) (LockSourceRow, error) {
	row := q.db.QueryRow(ctx, lockSource, id)
	var i LockSourceRow
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Kind,
		&i.ParticipationMode,
		&i.TrustTier,
		&i.Config,
		&i.CredentialRef,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.Checkpoint,
		&i.NextFetchAt,
		&i.LastSuccessAt,
		&i.FailureCount,
		&i.AutoUpdateFields,
		&i.AllowFulltext,
		&i.EditVersion,
	)
	return i, err
}

const lockSourceByKey = `-- name: LockSourceByKey :one
SELECT id, source_key, name, kind, participation_mode, trust_tier, config, credential_ref,
       enabled, interval_seconds, checkpoint, next_fetch_at, last_success_at, failure_count,
       auto_update_fields, allow_fulltext, edit_version
FROM sources
WHERE source_key = $1
FOR UPDATE
`

type LockSourceByKeyRow struct {
	ID                uuid.UUID
	SourceKey         string
	Name              string
	Kind              string
	ParticipationMode string
	TrustTier         string
	Config            json.RawMessage
	CredentialRef     *string
	Enabled           bool
	IntervalSeconds   int32
	Checkpoint        json.RawMessage
	NextFetchAt       pgtype.Timestamptz
	LastSuccessAt     pgtype.Timestamptz
	FailureCount      int32
	AutoUpdateFields  []string
	AllowFulltext     bool
	EditVersion       int64
}

func (q *Queries) LockSourceByKey(ctx context.Context, sourceKey string) (LockSourceByKeyRow, error) {
	row := q.db.QueryRow(ctx, lockSourceByKey, sourceKey)
	var i LockSourceByKeyRow
	err := row.Scan(
		&i.ID,
		&i.SourceKey,
		&i.Name,
		&i.Kind,
		&i.ParticipationMode,
		&i.TrustTier,
		&i.Config,
		&i.CredentialRef,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.Checkpoint,
		&i.NextFetchAt,
		&i.LastSuccessAt,
		&i.FailureCount,
		&i.AutoUpdateFields,
		&i.AllowFulltext,
		&i.EditVersion,
	)
	return i, err
}

const saveSourceCheckpoint = `-- name: SaveSourceCheckpoint :execrows
UPDATE sources
SET checkpoint = $1,
    last_success_at = $2,
    next_fetch_at = $3,
    failure_count = 0,
    updated_at = $4
WHERE id = $5
  AND edit_version = $6
`

type SaveSourceCheckpointParams struct {
	Checkpoint    json.RawMessage
	LastSuccessAt pgtype.Timestamptz
	NextFetchAt   pgtype.Timestamptz
	UpdatedAt     time.Time
	ID            uuid.UUID
	EditVersion   int64
}

func (q *Queries) SaveSourceCheckpoint(ctx context.Context, arg SaveSourceCheckpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveSourceCheckpoint,
		arg.Checkpoint,
		arg.LastSuccessAt,
		arg.NextFetchAt,
		arg.UpdatedAt,
		arg.ID,
		arg.EditVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSourceNextFetch = `-- name: SetSourceNextFetch :exec
UPDATE sources
SET next_fetch_at = $1,
    updated_at = $2
WHERE id = $3
`

type SetSourceNextFetchParams struct {
	NextFetchAt pgtype.Timestamptz
	UpdatedAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) SetSourceNextFetch(ctx context.Context, arg SetSourceNextFetchParams) error {
	_, err := q.db.Exec(ctx, setSourceNextFetch, arg.NextFetchAt, arg.UpdatedAt, arg.ID)
	return err
}
