// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proposals.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProposalsForRevision = `-- name: CountProposalsForRevision :one
SELECT count(*)::bigint
FROM change_proposals cp
JOIN processing_runs pr ON pr.id = cp.processing_run_id
WHERE pr.raw_revision_id = $1
`

func (q *Queries) CountProposalsForRevision(ctx context.Context, rawRevisionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProposalsForRevision, rawRevisionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findAppliedResourceForItem = `-- name: FindAppliedResourceForItem :one
SELECT cp.applied_resource_id
FROM change_proposals cp
JOIN processing_runs pr ON pr.id = cp.processing_run_id
JOIN raw_item_revisions rr ON rr.id = pr.raw_revision_id
JOIN resources r ON r.id = cp.applied_resource_id
WHERE rr.raw_item_id = $1
  AND r.kind = $2
  AND cp.applied_resource_id IS NOT NULL
ORDER BY cp.updated_at DESC
LIMIT 1
`

type FindAppliedResourceForItemParams struct {
	RawItemID uuid.UUID
	Kind      string
}

func (q *Queries) FindAppliedResourceForItem(ctx context.Context, arg FindAppliedResourceForItemParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAppliedResourceForItem, arg.RawItemID, arg.Kind)
	var applied_resource_id pgtype.UUID
	err := row.Scan(&applied_resource_id)
	return applied_resource_id, err
}

const findResourceByIdentity = `-- name: FindResourceByIdentity :one
SELECT id
FROM resources
WHERE kind = $1 AND identity_key = $2
`

type FindResourceByIdentityParams struct {
	Kind        string
	IdentityKey *string
}

func (q *Queries) FindResourceByIdentity(ctx context.Context, arg FindResourceByIdentityParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findResourceByIdentity, arg.Kind, arg.IdentityKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProposal = `-- name: GetProposal :one
SELECT id, processing_run_id, proposal_no, resource_id, base_edit_version, proposed_kind,
       proposed_payload, field_changes, status, review_decisions, reviewed_by, reviewed_at,
       applied_resource_id, applied_revision_id, created_at, updated_at
FROM change_proposals
WHERE id = $1
`

type GetProposalRow struct {
	ID                uuid.UUID
	ProcessingRunID   uuid.UUID
	ProposalNo        int32
	ResourceID        pgtype.UUID
	BaseEditVersion   *int64
	ProposedKind      string
	ProposedPayload   json.RawMessage
	FieldChanges      json.RawMessage
	Status            string
	ReviewDecisions   json.RawMessage
	ReviewedBy        pgtype.UUID
	ReviewedAt        pgtype.Timestamptz
	AppliedResourceID pgtype.UUID
	AppliedRevisionID pgtype.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) GetProposal(ctx context.Context, id uuid.UUID) (GetProposalRow, error) {
	row := q.db.QueryRow(ctx, getProposal, id)
	var i GetProposalRow
	err := row.Scan(
		&i.ID,
		&i.ProcessingRunID,
		&i.ProposalNo,
		&i.ResourceID,
		&i.BaseEditVersion,
		&i.ProposedKind,
		&i.ProposedPayload,
		&i.FieldChanges,
		&i.Status,
		&i.ReviewDecisions,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedResourceID,
		&i.AppliedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProposalByRun = `-- name: GetProposalByRun :one
SELECT id, status
FROM change_proposals
WHERE processing_run_id = $1 AND proposal_no = 1
`

type GetProposalByRunRow struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) GetProposalByRun(ctx context.Context, processingRunID uuid.UUID) (GetProposalByRunRow, error) {
	row := q.db.QueryRow(ctx, getProposalByRun, processingRunID)
	var i GetProposalByRunRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getPublication = `-- name: GetPublication :one
SELECT resource_id, revision_id, kind, title, aliases, summary, body_markdown, cover_urls,
       primary_category_id, quality_score, recommendation_reason, details
FROM resource_publications
WHERE resource_id = $1
`

type GetPublicationRow struct {
	ResourceID           uuid.UUID
	RevisionID           uuid.UUID
	Kind                 string
	Title                string
	Aliases              []string
	Summary              string
	BodyMarkdown         *string
	CoverUrls            []string
	PrimaryCategoryID    pgtype.UUID
	QualityScore         int16
	RecommendationReason *string
	Details              json.RawMessage
}

func (q *Queries) GetPublication(ctx context.Context, resourceID uuid.UUID) (GetPublicationRow, error) {
	row := q.db.QueryRow(ctx, getPublication, resourceID)
	var i GetPublicationRow
	err := row.Scan(
		&i.ResourceID,
		&i.RevisionID,
		&i.Kind,
		&i.Title,
		&i.Aliases,
		&i.Summary,
		&i.BodyMarkdown,
		&i.CoverUrls,
		&i.PrimaryCategoryID,
		&i.QualityScore,
		&i.RecommendationReason,
		&i.Details,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_logs (
    actor_admin_id, actor_type, action, target_type, target_id, changes, request_id, job_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertAuditParams struct {
	ActorAdminID pgtype.UUID
	ActorType    string
	Action       string
	TargetType   string
	TargetID     string
	Changes      json.RawMessage
	RequestID    *string
	JobID        *string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorAdminID,
		arg.ActorType,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Changes,
		arg.RequestID,
		arg.JobID,
	)
	return err
}

const insertEvidence = `-- name: InsertEvidence :exec
INSERT INTO resource_evidence (
    id, resource_id, resource_revision_id, proposal_id, raw_revision_id,
    field_path, evidence_excerpt, locator, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertEvidenceParams struct {
	ID                 uuid.UUID
	ResourceID         uuid.UUID
	ResourceRevisionID pgtype.UUID
	ProposalID         pgtype.UUID
	RawRevisionID      uuid.UUID
	FieldPath          string
	EvidenceExcerpt    *string
	Locator            json.RawMessage
	CreatedAt          time.Time
}

func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) error {
	_, err := q.db.Exec(ctx, insertEvidence,
		arg.ID,
		arg.ResourceID,
		arg.ResourceRevisionID,
		arg.ProposalID,
		arg.RawRevisionID,
		arg.FieldPath,
		arg.EvidenceExcerpt,
		arg.Locator,
		arg.CreatedAt,
	)
	return err
}

const insertProposal = `-- name: InsertProposal :one
INSERT INTO change_proposals (
    id, processing_run_id, proposal_no, resource_id, base_edit_version,
    proposed_kind, proposed_payload, field_changes, status, created_at, updated_at
) VALUES (
    $1, $2, 1, $3, $4, $5, $6, $7, 'pending', $8, $8
)
ON CONFLICT (processing_run_id, proposal_no) DO NOTHING
RETURNING id
`

type InsertProposalParams struct {
	ID              uuid.UUID
	ProcessingRunID uuid.UUID
	ResourceID      pgtype.UUID
	BaseEditVersion *int64
	ProposedKind    string
	ProposedPayload json.RawMessage
	FieldChanges    json.RawMessage
	CreatedAt       time.Time
}

func (q *Queries) InsertProposal(ctx context.Context, arg InsertProposalParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertProposal,
		arg.ID,
		arg.ProcessingRunID,
		arg.ResourceID,
		arg.BaseEditVersion,
		arg.ProposedKind,
		arg.ProposedPayload,
		arg.FieldChanges,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listProposalsByStatus = `-- name: ListProposalsByStatus :many
SELECT id, processing_run_id, resource_id, base_edit_version, proposed_kind,
       proposed_payload, field_changes, status, created_at, updated_at
FROM change_proposals
WHERE status = $1
ORDER BY created_at DESC, id
LIMIT 200
`

type ListProposalsByStatusRow struct {
	ID              uuid.UUID
	ProcessingRunID uuid.UUID
	ResourceID      pgtype.UUID
	BaseEditVersion *int64
	ProposedKind    string
	ProposedPayload json.RawMessage
	FieldChanges    json.RawMessage
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListProposalsByStatus(ctx context.Context, status string) ([]ListProposalsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listProposalsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProposalsByStatusRow
	for rows.Next() {
		var i ListProposalsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ProcessingRunID,
			&i.ResourceID,
			&i.BaseEditVersion,
			&i.ProposedKind,
			&i.ProposedPayload,
			&i.FieldChanges,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationTagIDs = `-- name: ListPublicationTagIDs :many
SELECT tag_id
FROM resource_tags
WHERE resource_id = $1
ORDER BY tag_id
`

func (q *Queries) ListPublicationTagIDs(ctx context.Context, resourceID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPublicationTagIDs, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var tag_id uuid.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProposal = `-- name: LockProposal :one
SELECT id, processing_run_id, proposal_no, resource_id, base_edit_version, proposed_kind,
       proposed_payload, field_changes, status, review_decisions, reviewed_by, reviewed_at,
       applied_resource_id, applied_revision_id, created_at, updated_at
FROM change_proposals
WHERE id = $1
FOR UPDATE
`

type LockProposalRow struct {
	ID                uuid.UUID
	ProcessingRunID   uuid.UUID
	ProposalNo        int32
	ResourceID        pgtype.UUID
	BaseEditVersion   *int64
	ProposedKind      string
	ProposedPayload   json.RawMessage
	FieldChanges      json.RawMessage
	Status            string
	ReviewDecisions   json.RawMessage
	ReviewedBy        pgtype.UUID
	ReviewedAt        pgtype.Timestamptz
	AppliedResourceID pgtype.UUID
	AppliedRevisionID pgtype.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) LockProposal(ctx context.Context, id uuid.UUID) (LockProposalRow, error) {
	row := q.db.QueryRow(ctx, lockProposal, id)
	var i LockProposalRow
	err := row.Scan(
		&i.ID,
		&i.ProcessingRunID,
		&i.ProposalNo,
		&i.ResourceID,
		&i.BaseEditVersion,
		&i.ProposedKind,
		&i.ProposedPayload,
		&i.FieldChanges,
		&i.Status,
		&i.ReviewDecisions,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedResourceID,
		&i.AppliedRevisionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockResource = `-- name: LockResource :one
SELECT id, kind, identity_key, slug, status, draft_revision_id, edit_version, field_locks
FROM resources
WHERE id = $1
FOR UPDATE
`

type LockResourceRow struct {
	ID              uuid.UUID
	Kind            string
	IdentityKey     *string
	Slug            string
	Status          string
	DraftRevisionID pgtype.UUID
	EditVersion     int64
	FieldLocks      []string
}

func (q *Queries) LockResource(ctx context.Context, id uuid.UUID) (LockResourceRow, error) {
	row := q.db.QueryRow(ctx, lockResource, id)
	var i LockResourceRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IdentityKey,
		&i.Slug,
		&i.Status,
		&i.DraftRevisionID,
		&i.EditVersion,
		&i.FieldLocks,
	)
	return i, err
}

const updateProposalReview = `-- name: UpdateProposalReview :exec
UPDATE change_proposals
SET status = $2,
    review_decisions = $3,
    reviewed_by = $4,
    reviewed_at = $5,
    applied_resource_id = $6,
    applied_revision_id = $7,
    updated_at = $5
WHERE id = $1
`

type UpdateProposalReviewParams struct {
	ID                uuid.UUID
	Status            string
	ReviewDecisions   json.RawMessage
	ReviewedBy        pgtype.UUID
	ReviewedAt        pgtype.Timestamptz
	AppliedResourceID pgtype.UUID
	AppliedRevisionID pgtype.UUID
}

func (q *Queries) UpdateProposalReview(ctx context.Context, arg UpdateProposalReviewParams) error {
	_, err := q.db.Exec(ctx, updateProposalReview,
		arg.ID,
		arg.Status,
		arg.ReviewDecisions,
		arg.ReviewedBy,
		arg.ReviewedAt,
		arg.AppliedResourceID,
		arg.AppliedRevisionID,
	)
	return err
}
