// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveTag = `-- name: FindActiveTag :one
SELECT t.id
FROM tags t
LEFT JOIN tag_aliases a ON a.tag_id = t.id AND a.dimension = t.dimension
WHERE t.status = 'active'
  AND (
    lower(btrim(t.name)) = lower(btrim($1))
    OR lower(btrim(a.alias)) = lower(btrim($1))
    OR a.normalized_alias = lower(btrim($1))
  )
ORDER BY t.id
LIMIT 1
`

func (q *Queries) FindActiveTag(ctx context.Context, btrim string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findActiveTag, btrim)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getRawRevision = `-- name: GetRawRevision :one
SELECT id, raw_item_id, revision_no, content_hash, title, excerpt, body_text, body_html, language, raw_payload
FROM raw_item_revisions
WHERE id = $1
`

type GetRawRevisionRow struct {
	ID          uuid.UUID
	RawItemID   uuid.UUID
	RevisionNo  int64
	ContentHash string
	Title       string
	Excerpt     *string
	BodyText    *string
	BodyHtml    *string
	Language    *string
	RawPayload  json.RawMessage
}

func (q *Queries) GetRawRevision(ctx context.Context, id uuid.UUID) (GetRawRevisionRow, error) {
	row := q.db.QueryRow(ctx, getRawRevision, id)
	var i GetRawRevisionRow
	err := row.Scan(
		&i.ID,
		&i.RawItemID,
		&i.RevisionNo,
		&i.ContentHash,
		&i.Title,
		&i.Excerpt,
		&i.BodyText,
		&i.BodyHtml,
		&i.Language,
		&i.RawPayload,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, raw_revision_id, stage, pipeline_key, pipeline_plan, input_hash, rule_version,
       rerun_no, run_key, status, output, error_code, error_message, attempt_count
FROM processing_runs
WHERE id = $1
`

type GetRunRow struct {
	ID            uuid.UUID
	RawRevisionID uuid.UUID
	Stage         string
	PipelineKey   string
	PipelinePlan  json.RawMessage
	InputHash     string
	RuleVersion   string
	RerunNo       int32
	RunKey        string
	Status        string
	Output        []byte
	ErrorCode     *string
	ErrorMessage  *string
	AttemptCount  int32
}

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.RawRevisionID,
		&i.Stage,
		&i.PipelineKey,
		&i.PipelinePlan,
		&i.InputHash,
		&i.RuleVersion,
		&i.RerunNo,
		&i.RunKey,
		&i.Status,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AttemptCount,
	)
	return i, err
}

const getRunByStage = `-- name: GetRunByStage :one
SELECT id, raw_revision_id, stage, pipeline_key, pipeline_plan, input_hash, rule_version,
       rerun_no, run_key, status, output, error_code, error_message, attempt_count
FROM processing_runs
WHERE raw_revision_id = $1 AND pipeline_key = $2 AND stage = $3
`

type GetRunByStageParams struct {
	RawRevisionID uuid.UUID
	PipelineKey   string
	Stage         string
}

type GetRunByStageRow struct {
	ID            uuid.UUID
	RawRevisionID uuid.UUID
	Stage         string
	PipelineKey   string
	PipelinePlan  json.RawMessage
	InputHash     string
	RuleVersion   string
	RerunNo       int32
	RunKey        string
	Status        string
	Output        []byte
	ErrorCode     *string
	ErrorMessage  *string
	AttemptCount  int32
}

func (q *Queries) GetRunByStage(ctx context.Context, arg GetRunByStageParams) (GetRunByStageRow, error) {
	row := q.db.QueryRow(ctx, getRunByStage, arg.RawRevisionID, arg.PipelineKey, arg.Stage)
	var i GetRunByStageRow
	err := row.Scan(
		&i.ID,
		&i.RawRevisionID,
		&i.Stage,
		&i.PipelineKey,
		&i.PipelinePlan,
		&i.InputHash,
		&i.RuleVersion,
		&i.RerunNo,
		&i.RunKey,
		&i.Status,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AttemptCount,
	)
	return i, err
}

const getSource = `-- name: GetSource :one
SELECT id, kind, auto_update_fields
FROM sources
WHERE id = $1
`

type GetSourceRow struct {
	ID               uuid.UUID
	Kind             string
	AutoUpdateFields []string
}

func (q *Queries) GetSource(ctx context.Context, id uuid.UUID) (GetSourceRow, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i GetSourceRow
	err := row.Scan(&i.ID, &i.Kind, &i.AutoUpdateFields)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO processing_runs (
    id, raw_revision_id, stage, pipeline_key, pipeline_plan,
    input_hash, rule_version, rerun_no, run_key, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending', $10, $10
)
ON CONFLICT (raw_revision_id, pipeline_key, stage) DO NOTHING
RETURNING id
`

type InsertRunParams struct {
	ID            uuid.UUID
	RawRevisionID uuid.UUID
	Stage         string
	PipelineKey   string
	PipelinePlan  json.RawMessage
	InputHash     string
	RuleVersion   string
	RerunNo       int32
	RunKey        string
	CreatedAt     time.Time
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRun,
		arg.ID,
		arg.RawRevisionID,
		arg.Stage,
		arg.PipelineKey,
		arg.PipelinePlan,
		arg.InputHash,
		arg.RuleVersion,
		arg.RerunNo,
		arg.RunKey,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listRunsForItem = `-- name: ListRunsForItem :many
SELECT pr.id, pr.raw_revision_id, pr.stage, pr.pipeline_key, pr.status, pr.rule_version,
       pr.run_key, pr.input_hash, pr.error_code, pr.output
FROM processing_runs pr
JOIN raw_item_revisions rr ON rr.id = pr.raw_revision_id
WHERE rr.raw_item_id = $1
ORDER BY pr.created_at, pr.stage
`

type ListRunsForItemRow struct {
	ID            uuid.UUID
	RawRevisionID uuid.UUID
	Stage         string
	PipelineKey   string
	Status        string
	RuleVersion   string
	RunKey        string
	InputHash     string
	ErrorCode     *string
	Output        []byte
}

func (q *Queries) ListRunsForItem(ctx context.Context, rawItemID uuid.UUID) ([]ListRunsForItemRow, error) {
	rows, err := q.db.Query(ctx, listRunsForItem, rawItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsForItemRow
	for rows.Next() {
		var i ListRunsForItemRow
		if err := rows.Scan(
			&i.ID,
			&i.RawRevisionID,
			&i.Stage,
			&i.PipelineKey,
			&i.Status,
			&i.RuleVersion,
			&i.RunKey,
			&i.InputHash,
			&i.ErrorCode,
			&i.Output,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRawItem = `-- name: LockRawItem :one
SELECT id, owner_source_id, identity_key, canonical_url, current_revision_id
FROM raw_items
WHERE id = $1
FOR UPDATE
`

type LockRawItemRow struct {
	ID                uuid.UUID
	OwnerSourceID     uuid.UUID
	IdentityKey       string
	CanonicalUrl      *string
	CurrentRevisionID pgtype.UUID
}

func (q *Queries) LockRawItem(ctx context.Context, id uuid.UUID) (LockRawItemRow, error) {
	row := q.db.QueryRow(ctx, lockRawItem, id)
	var i LockRawItemRow
	err := row.Scan(
		&i.ID,
		&i.OwnerSourceID,
		&i.IdentityKey,
		&i.CanonicalUrl,
		&i.CurrentRevisionID,
	)
	return i, err
}

const lockRun = `-- name: LockRun :one
SELECT id, raw_revision_id, stage, pipeline_key, pipeline_plan, input_hash, rule_version,
       rerun_no, run_key, status, output, error_code, error_message, attempt_count
FROM processing_runs
WHERE id = $1
FOR UPDATE
`

type LockRunRow struct {
	ID            uuid.UUID
	RawRevisionID uuid.UUID
	Stage         string
	PipelineKey   string
	PipelinePlan  json.RawMessage
	InputHash     string
	RuleVersion   string
	RerunNo       int32
	RunKey        string
	Status        string
	Output        []byte
	ErrorCode     *string
	ErrorMessage  *string
	AttemptCount  int32
}

func (q *Queries) LockRun(ctx context.Context, id uuid.UUID) (LockRunRow, error) {
	row := q.db.QueryRow(ctx, lockRun, id)
	var i LockRunRow
	err := row.Scan(
		&i.ID,
		&i.RawRevisionID,
		&i.Stage,
		&i.PipelineKey,
		&i.PipelinePlan,
		&i.InputHash,
		&i.RuleVersion,
		&i.RerunNo,
		&i.RunKey,
		&i.Status,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AttemptCount,
	)
	return i, err
}

const lockTaxonomyShared = `-- name: LockTaxonomyShared :exec
SELECT pg_advisory_xact_lock_shared(1313821761::int4, 1::int4)
`

func (q *Queries) LockTaxonomyShared(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockTaxonomyShared)
	return err
}

const markRunRunning = `-- name: MarkRunRunning :execrows
UPDATE processing_runs
SET status = 'running',
    attempt_count = attempt_count + 1,
    started_at = COALESCE(started_at, $2),
    updated_at = $2
WHERE id = $1 AND status IN ('pending', 'running', 'failed')
`

type MarkRunRunningParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
}

func (q *Queries) MarkRunRunning(ctx context.Context, arg MarkRunRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRunRunning, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveRunBlocked = `-- name: SaveRunBlocked :execrows
UPDATE processing_runs
SET status = 'blocked',
    output = $2,
    error_code = $3,
    error_message = $4,
    finished_at = $5,
    updated_at = $5
WHERE id = $1 AND status IN ('pending', 'running', 'failed')
`

type SaveRunBlockedParams struct {
	ID           uuid.UUID
	Output       []byte
	ErrorCode    *string
	ErrorMessage *string
	FinishedAt   pgtype.Timestamptz
}

func (q *Queries) SaveRunBlocked(ctx context.Context, arg SaveRunBlockedParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveRunBlocked,
		arg.ID,
		arg.Output,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveRunFailed = `-- name: SaveRunFailed :execrows
UPDATE processing_runs
SET status = 'failed',
    output = $2,
    error_code = $3,
    error_message = $4,
    finished_at = $5,
    updated_at = $5
WHERE id = $1 AND status IN ('pending', 'running', 'failed')
`

type SaveRunFailedParams struct {
	ID           uuid.UUID
	Output       []byte
	ErrorCode    *string
	ErrorMessage *string
	FinishedAt   pgtype.Timestamptz
}

func (q *Queries) SaveRunFailed(ctx context.Context, arg SaveRunFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveRunFailed,
		arg.ID,
		arg.Output,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveRunStale = `-- name: SaveRunStale :execrows
UPDATE processing_runs
SET status = 'stale',
    output = $2,
    finished_at = $3,
    updated_at = $3
WHERE id = $1 AND status IN ('pending', 'running', 'failed')
`

type SaveRunStaleParams struct {
	ID         uuid.UUID
	Output     []byte
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) SaveRunStale(ctx context.Context, arg SaveRunStaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveRunStale, arg.ID, arg.Output, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveRunSucceeded = `-- name: SaveRunSucceeded :execrows
UPDATE processing_runs
SET status = 'succeeded',
    output = $2,
    error_code = NULL,
    error_message = NULL,
    finished_at = $3,
    updated_at = $3
WHERE id = $1 AND status IN ('pending', 'running', 'failed')
`

type SaveRunSucceededParams struct {
	ID         uuid.UUID
	Output     []byte
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) SaveRunSucceeded(ctx context.Context, arg SaveRunSucceededParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveRunSucceeded, arg.ID, arg.Output, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
